# <font color = red> Pandas básico

La biblioteca de software de código abierto Pandas está diseñada específicamente para la manipulación y el análisis de datos en el lenguaje Python. Es potente, flexible y fácil de usar. El nombre **Pandas** es en realidad una contracción del término «Panel Data» para series de datos que incluyen observaciones a lo largo de varios periodos de tiempo. La biblioteca se creó como herramienta de alto nivel para el análisis en Python.

<center> <img src = "pandas.png" width="200"></center>

## <font color = darkblue>  Configurar pandas e importarlo

En caso de no tener instalado Pandas se puede instalar en Windows usando *!pip install pandas*. Después de instalarlo, se utiliza el siguiente comando para utilizar este módulo y llamar todas las funciones de pandas.

In [2]:
import pandas as pd
print(pd.__version__)

2.3.3

## <font color = darkblue> Creacion de estructuras básicas en Pandas 

Las estructuras básicas en Pandas son Series (unidimensional etiquetada) y DataFrame (bidimensional, tipo tabla). Las Series almacenan datos homogéneos con etiquetas, mientras que los DataFrames organizan datos en filas y columnas, permitiendo tipos distintos por columna, similares a una hoja de cálculo. Ambas son fundamentales para la manipulación y análisis de datos.

### Creando una Series a partir de una lista

In [2]:
carros = ['Jetta Variant', 'Passat', 'Crossfox']
carros

['Jetta Variant', 'Passat', 'Crossfox']

In [3]:
Serie = pd.Series(carros)
print(Serie)

0    Jetta Variant
1           Passat
2         Crossfox
dtype: object

### Creando un DataFrame a partir de una lista de diccionarios

In [4]:
datos = [
    {'Nombre': 'Jetta Variant', 'Motor': 'Motor 4.0 Turbo', 'Año': 2003, 'Kilometraje': 44410.0, 'Cero_km': False, 'Valor': 88078.64},
    {'Nombre': 'Passat', 'Motor': 'Motor Diesel', 'Año': 1991, 'Kilometraje': 5712.0, 'Cero_km': False, 'Valor': 106161.94},
    {'Nombre': 'Crossfox', 'Motor': 'Motor Diesel V8', 'Año': 1990, 'Kilometraje': 37123.0, 'Cero_km': False, 'Valor': 72832.16}
]
print(datos)

[{'Nombre': 'Jetta Variant', 'Motor': 'Motor 4.0 Turbo', 'Año': 2003, 'Kilometraje': 44410.0, 'Cero_km': False, 'Valor': 88078.64}, {'Nombre': 'Passat', 'Motor': 'Motor Diesel', 'Año': 1991, 'Kilometraje': 5712.0, 'Cero_km': False, 'Valor': 106161.94}, {'Nombre': 'Crossfox', 'Motor': 'Motor Diesel V8', 'Año': 1990, 'Kilometraje': 37123.0, 'Cero_km': False, 'Valor': 72832.16}]

In [5]:
# Utilizar pandas para obtener la estructura de dataframe
dataset = pd.DataFrame(datos)
dataset

          Nombre            Motor   Año  Kilometraje  Cero_km      Valor
0  Jetta Variant  Motor 4.0 Turbo  2003      44410.0    False   88078.64
1         Passat     Motor Diesel  1991       5712.0    False  106161.94
2       Crossfox  Motor Diesel V8  1990      37123.0    False   72832.16

### Creando un DataFrame a partir de un diccionario

In [6]:
datos = {
    'Nombre': ['Jetta Variant', 'Passat', 'Crossfox'], 
    'Motor': ['Motor 4.0 Turbo', 'Motor Diesel', 'Motor Diesel V8'],
    'Año': [2003, 1991, 1990],
    'Kilometraje': [44410.0, 5712.0, 37123.0],
    'Cero_km': [False, False, False],
    'Valor': [88078.64, 106161.94, 72832.16]
}

In [7]:
# Utilizar pandas para obtener la estructura de dataframe
dataset = pd.DataFrame(datos)
dataset

          Nombre            Motor   Año  Kilometraje  Cero_km      Valor
0  Jetta Variant  Motor 4.0 Turbo  2003      44410.0    False   88078.64
1         Passat     Motor Diesel  1991       5712.0    False  106161.94
2       Crossfox  Motor Diesel V8  1990      37123.0    False   72832.16

## <font color = darkblue> Lectura de archivos externos

Pandas facilita la lectura de archivos externos (locales o en red) convirtiéndolos en DataFrames mediante funciones read_*.

### Lectura csv

Un archivo CSV (Comma Separated Values o Valores Separados por Comas) es un archivo de texto plano que almacena datos estructurados en forma de tabla, donde cada línea representa una fila y las comas (o puntos y coma) separan las columnas. Es un formato universal, ligero y compatible con hojas de cálculo como Excel y bases de datos. 

La lectura de csv contiene los siguientes campos

In [8]:
df = pd.read_csv(
    "Ecommerce.csv",
    sep = ",",           # separador
    encoding = "utf-8",  # codificación
    header = 0,          # fila de encabezados 0 si la tiene, 1 si NO la tiene
    index_col = None     # Se coloca la columna indice
)

print(df)

       TransactionNo       Date ProductNo  \
0             581482  12/9/2019     22485
1             581475  12/9/2019     22596
2             581475  12/9/2019     23235
3             581475  12/9/2019     23272
4             581475  12/9/2019     23239
...              ...        ...       ...
536345       C536548  12/1/2018     22168
536346       C536548  12/1/2018     21218
536347       C536548  12/1/2018     20957
536348       C536548  12/1/2018     22580
536349       C536548  12/1/2018     22767

                                ProductName  Price  Quantity  CustomerNo  \
0             Set Of 2 Wooden Market Crates  21.47        12     17490.0
1       Christmas Star Wish List Chalkboard  10.65        36     13069.0
2                  Storage Tin Vintage Leaf  11.53        12     13069.0
3         Tree T-Light Holder Willie Winkie  10.65        12     13069.0
4         Set Of 4 Knick Knack Tins Poppies  11.94         6     13069.0
...                                     ...    ...       ...         ...
536345         Organiser Wood Antique White  18.96        -2     12472.0
536346               Red Spotty Biscuit Tin  14.09        -3     12472.0
536347         Porcelain Hanging Bell Small  11.74        -1     12472.0
536348         Advent Calendar Gingham Sack  16.35        -4     12472.0
536349           Triple Photo Frame Cornice  20.45        -2     12472.0

               Country
0       United Kingdom
1       United Kingdom
2       United Kingdom
3       United Kingdom
4       United Kingdom
...                ...
536345         Germany
536346         Germany
536347         Germany
536348         Germany
536349         Germany

[536350 rows x 8 columns]

En el siguiente dataset si se quiere convertir automáticamente una columna especificada en un objeto del tipo datetime.

In [9]:
dataset = pd.read_csv(
    'avocado.csv',            # Nombre del archivo
    sep = ',',                # Separador
    header = 0,               # Si tiene encabezado
    parse_dates = ['Date']    # Se convierte la columna date en fechas (importante series de tiempo)
)

# Imprimir primeras filas
print(dataset)

       Unnamed: 0       Date  AveragePrice  Total Volume     4046       4225  \
0               0 2015-12-27          1.33      64236.62  1036.74   54454.85
1               1 2015-12-20          1.35      54876.98   674.28   44638.81
2               2 2015-12-13          0.93     118220.22   794.70  109149.67
3               3 2015-12-06          1.08      78992.15  1132.00   71976.41
4               4 2015-11-29          1.28      51039.60   941.48   43838.39
...           ...        ...           ...           ...      ...        ...
18244           7 2018-02-04          1.63      17074.83  2046.96    1529.20
18245           8 2018-01-28          1.71      13888.04  1191.70    3431.50
18246           9 2018-01-21          1.87      13766.76  1191.92    2452.79
18247          10 2018-01-14          1.93      16205.22  1527.63    2981.04
18248          11 2018-01-07          1.62      17489.58  2894.77    2356.13

         4770  Total Bags  Small Bags  Large Bags  XLarge Bags          type  \
0       48.16     8696.87     8603.62       93.25          0.0  conventional
1       58.33     9505.56     9408.07       97.49          0.0  conventional
2      130.50     8145.35     8042.21      103.14          0.0  conventional
3       72.58     5811.16     5677.40      133.76          0.0  conventional
4       75.78     6183.95     5986.26      197.69          0.0  conventional
...       ...         ...         ...         ...          ...           ...
18244    0.00    13498.67    13066.82      431.85          0.0       organic
18245    0.00     9264.84     8940.04      324.80          0.0       organic
18246  727.94     9394.11     9351.80       42.31          0.0       organic
18247  727.01    10969.54    10919.54       50.00          0.0       organic
18248  224.53    12014.15    11988.14       26.01          0.0       organic

       year            region
0      2015            Albany
1      2015            Albany
2      2015            Albany
3      2015            Albany
4      2015            Albany
...     ...               ...
18244  2018  WestTexNewMexico
18245  2018  WestTexNewMexico
18246  2018  WestTexNewMexico
18247  2018  WestTexNewMexico
18248  2018  WestTexNewMexico

[18249 rows x 14 columns]

Cuando hay problemas de encoding (muy comúnes) se utiliza en ese parámetro la palabra "latin-1"

In [10]:
df = pd.read_csv(
    "Ecommerce.csv",
    sep = ",",             # separador
    encoding = "latin-1",  # codificación
    header = 0,            # fila de encabezados 0 si la tiene en la primera fila, None si no tiene
    index_col = None       # Se coloca la columna indice
)

print(df)

       TransactionNo       Date ProductNo  \
0             581482  12/9/2019     22485
1             581475  12/9/2019     22596
2             581475  12/9/2019     23235
3             581475  12/9/2019     23272
4             581475  12/9/2019     23239
...              ...        ...       ...
536345       C536548  12/1/2018     22168
536346       C536548  12/1/2018     21218
536347       C536548  12/1/2018     20957
536348       C536548  12/1/2018     22580
536349       C536548  12/1/2018     22767

                                ProductName  Price  Quantity  CustomerNo  \
0             Set Of 2 Wooden Market Crates  21.47        12     17490.0
1       Christmas Star Wish List Chalkboard  10.65        36     13069.0
2                  Storage Tin Vintage Leaf  11.53        12     13069.0
3         Tree T-Light Holder Willie Winkie  10.65        12     13069.0
4         Set Of 4 Knick Knack Tins Poppies  11.94         6     13069.0
...                                     ...    ...       ...         ...
536345         Organiser Wood Antique White  18.96        -2     12472.0
536346               Red Spotty Biscuit Tin  14.09        -3     12472.0
536347         Porcelain Hanging Bell Small  11.74        -1     12472.0
536348         Advent Calendar Gingham Sack  16.35        -4     12472.0
536349           Triple Photo Frame Cornice  20.45        -2     12472.0

               Country
0       United Kingdom
1       United Kingdom
2       United Kingdom
3       United Kingdom
4       United Kingdom
...                ...
536345         Germany
536346         Germany
536347         Germany
536348         Germany
536349         Germany

[536350 rows x 8 columns]

### Lectura de archivos xlsx

Los archivos **xlsx** son el formato estándar de hojas de cálculo de Microsoft Excel (desde la versión 2007) utilizado para organizar, analizar y almacenar datos en filas y columnas. Basados en tecnología XML, son más livianos, seguros y compatibles que los antiguos .XLS, permitiendo fórmulas, gráficos y tablas.

In [11]:
df = pd.read_excel("Disenos.xlsx")
print(df)

       PET    Wood   EGMA  Particle_size  Mixing_times  Tensile
0   0.6000  0.4000  0.000             -1            -1     1.37
1   0.6000  0.3700  0.030             -1            -1     1.42
2   0.9000  0.1000  0.000             -1            -1     1.68
3   0.8700  0.1000  0.030             -1            -1     1.66
4   0.7425  0.2425  0.015             -1            -1     1.54
5   0.6000  0.4000  0.000              1            -1     1.68
6   0.6000  0.3700  0.030              1            -1     1.72
7   0.9000  0.1000  0.000              1            -1     2.46
8   0.8700  0.1000  0.030              1            -1     2.40
9   0.7425  0.2425  0.015              1            -1     2.03
10  0.6000  0.4000  0.000             -1             1     2.07
11  0.6000  0.3700  0.030             -1             1     2.08
12  0.9000  0.1000  0.000             -1             1     2.70
13  0.8700  0.1000  0.030             -1             1     2.66
14  0.7425  0.2425  0.015             -1             1     2.35
15  0.6000  0.4000  0.000              1             1     3.49
16  0.6000  0.3700  0.030              1             1     3.57
17  0.9000  0.1000  0.000              1             1     3.60
18  0.8700  0.1000  0.030              1             1     3.55
19  0.7425  0.2425  0.015              1             1     3.01

Leer una hoja en específico

In [12]:
df = pd.read_excel(
    "Disenos.xlsx",        # Nombre del archivo
    sheet_name="YouTube"   # Nombre de la hoja
)
print(df)

          x1        x2        x3  z1  z2  z3     y
0   1.000000  0.000000  0.000000  -1  -1  -1  1.84
1   0.000000  1.000000  0.000000  -1  -1  -1  0.67
2   0.000000  0.000000  1.000000  -1  -1  -1  1.51
3   0.500000  0.500000  0.000000  -1  -1  -1  1.29
4   0.500000  0.000000  0.500000  -1  -1  -1  1.42
5   0.000000  0.500000  0.500000  -1  -1  -1  1.61
6   0.333333  0.333333  0.333333  -1  -1  -1  1.59
7   1.000000  0.000000  0.000000   1  -1  -1  2.86
8   0.000000  1.000000  0.000000   1  -1  -1  1.10
9   0.000000  0.000000  1.000000   1  -1  -1  1.60
10  0.500000  0.500000  0.000000   1  -1  -1  1.53
11  0.500000  0.000000  0.500000   1  -1  -1  1.81
12  0.000000  0.500000  0.500000   1  -1  -1  1.50
13  0.333333  0.333333  0.333333   1  -1  -1  1.68
14  1.000000  0.000000  0.000000  -1   1  -1  3.01
15  0.000000  1.000000  0.000000  -1   1  -1  1.21
16  0.000000  0.000000  1.000000  -1   1  -1  2.32
17  0.500000  0.500000  0.000000  -1   1  -1  1.93
18  0.500000  0.000000  0.500000  -1   1  -1  2.57
19  0.000000  0.500000  0.500000  -1   1  -1  1.83
20  0.333333  0.333333  0.333333  -1   1  -1  1.94
21  1.000000  0.000000  0.000000   1   1  -1  4.13
22  0.000000  1.000000  0.000000   1   1  -1  1.67
23  0.000000  0.000000  1.000000   1   1  -1  2.57
24  0.500000  0.500000  0.000000   1   1  -1  2.26
25  0.500000  0.000000  0.500000   1   1  -1  3.15
26  0.000000  0.500000  0.500000   1   1  -1  2.22
27  0.333333  0.333333  0.333333   1   1  -1  2.60
28  1.000000  0.000000  0.000000  -1  -1   1  1.65
29  0.000000  1.000000  0.000000  -1  -1   1  0.58
30  0.000000  0.000000  1.000000  -1  -1   1  1.21
31  0.500000  0.500000  0.000000  -1  -1   1  1.18
32  0.500000  0.000000  0.500000  -1  -1   1  1.45
33  0.000000  0.500000  0.500000  -1  -1   1  1.07
34  0.333333  0.333333  0.333333  -1  -1   1  1.41
35  1.000000  0.000000  0.000000   1  -1   1  2.32
36  0.000000  1.000000  0.000000   1  -1   1  0.97
37  0.000000  0.000000  1.000000   1  -1   1  2.12
38  0.500000  0.500000  0.000000   1  -1   1  1.45
39  0.500000  0.000000  0.500000   1  -1   1  1.93
40  0.000000  0.500000  0.500000   1  -1   1  1.28
41  0.333333  0.333333  0.333333   1  -1   1  1.54
42  1.000000  0.000000  0.000000  -1   1   1  3.04
43  0.000000  1.000000  0.000000  -1   1   1  1.16
44  0.000000  0.000000  1.000000  -1   1   1  2.00
45  0.500000  0.500000  0.000000  -1   1   1  1.85
46  0.500000  0.000000  0.500000  -1   1   1  2.39
47  0.000000  0.500000  0.500000  -1   1   1  1.60
48  0.333333  0.333333  0.333333  -1   1   1  2.05
49  1.000000  0.000000  0.000000   1   1   1  4.13
50  0.000000  1.000000  0.000000   1   1   1  1.30
51  0.000000  0.000000  1.000000   1   1   1  2.75
52  0.500000  0.500000  0.000000   1   1   1  2.06
53  0.500000  0.000000  0.500000   1   1   1  2.82
54  0.000000  0.500000  0.500000   1   1   1  2.10
55  0.333333  0.333333  0.333333   1   1   1  2.32

Leer múltiples hojas

In [13]:
dfs = pd.read_excel(
    "Disenos.xlsx",    # Nombre del archivo
    sheet_name=None    # None para leer todas las hojas
)

# Acceder a una hoja
print(dfs["Wood"].head())
print(dfs["YouTube"].head())

      PET    Wood   EGMA  Particle_size  Mixing_times  Tensile
0  0.6000  0.4000  0.000             -1            -1     1.37
1  0.6000  0.3700  0.030             -1            -1     1.42
2  0.9000  0.1000  0.000             -1            -1     1.68
3  0.8700  0.1000  0.030             -1            -1     1.66
4  0.7425  0.2425  0.015             -1            -1     1.54
    x1   x2   x3  z1  z2  z3     y
0  1.0  0.0  0.0  -1  -1  -1  1.84
1  0.0  1.0  0.0  -1  -1  -1  0.67
2  0.0  0.0  1.0  -1  -1  -1  1.51
3  0.5  0.5  0.0  -1  -1  -1  1.29
4  0.5  0.0  0.5  -1  -1  -1  1.42

### Lectura de archivos txt

Los archivos .txt son documentos de texto plano que contienen caracteres alfanuméricos, letras y puntuación, sin formato especial como negritas, tamaños de fuente o imágenes. Son universales, ligeros y compatibles con casi cualquier sistema operativo (Windows, macOS, Linux). Se editan con programas básicos como el Bloc de notas.

In [14]:
# Leer txt con read_csv
df = pd.read_csv(
    'titanic.txt',      # Nombre del archivo
    sep=';',            # El formato de separacion
    header=0,           # Indica la fila del encabezado
    encoding= "utf-8"   # Tipo de decodificacion del archivo
)
print(df)

     Id_Pasajero  Survived  Clase  \
0              1         0      3
1              2         1      1
2              3         1      3
3              4         1      1
4              5         0      3
..           ...       ...    ...
886          887         0      2
887          888         1      1
888          889         0      3
889          890         1      1
890          891         0      3

                                                Nombre       Sexo  Edad  \
0                              Braund, Mr. Owen Harris  Masculino  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...   Femenino  38.0
2                               Heikkinen, Miss. Laina   Femenino  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)   Femenino  35.0
4                             Allen, Mr. William Henry  Masculino  35.0
..                                                 ...        ...   ...
886                              Montvila, Rev. Juozas  Masculino  27.0
887                       Graham, Miss. Margaret Edith   Femenino  19.0
888           Johnston, Miss. Catherine Helen "Carrie"   Femenino   NaN
889                              Behr, Mr. Karl Howell  Masculino  26.0
890                                Dooley, Mr. Patrick  Masculino  32.0

     Familiares           Tiquete  Tarifa Cabina Embarcado
0             0         A/5 21171    7.25    NaN         S
1             0          PC 17599   71.28    C85         C
2             0  STON/O2. 3101282    7.93    NaN         S
3             0            113803   53.10   C123         S
4             0            373450    8.05    NaN         S
..          ...               ...     ...    ...       ...
886           0            211536   13.00    NaN         S
887           0            112053   30.00    B42         S
888           2        W./C. 6607   23.45    NaN         S
889           0            111369   30.00   C148         C
890           0            370376    7.75    NaN         Q

[891 rows x 11 columns]

### Lectura de archivos HTML

HTML (HyperText Markup Language) es el lenguaje estándar utilizado para estructurar y crear el contenido de las páginas web. Utiliza un sistema de etiquetas (marcado) para definir elementos como párrafos, títulos, imágenes y enlaces, permitiendo a los navegadores interpretar y mostrar la información organizada jerárquicamente.

In [15]:
df = pd.read_html(
    "titanic.html"     # Nombre del archivo
)

print(df)

[     Unnamed: 0  Id_Pasajero  Survived  Clase  \
0             0            1         0      3
1             1            2         1      1
2             2            3         1      3
3             3            4         1      1
4             4            5         0      3
..          ...          ...       ...    ...
886         886          887         0      2
887         887          888         1      1
888         888          889         0      3
889         889          890         1      1
890         890          891         0      3

                                                Nombre       Sexo  Edad  \
0                              Braund, Mr. Owen Harris  Masculino  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...   Femenino  38.0
2                               Heikkinen, Miss. Laina   Femenino  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)   Femenino  35.0
4                             Allen, Mr. William Henry  Masculino  35.0
..                                                 ...        ...   ...
886                              Montvila, Rev. Juozas  Masculino  27.0
887                       Graham, Miss. Margaret Edith   Femenino  19.0
888           Johnston, Miss. Catherine Helen "Carrie"   Femenino   NaN
889                              Behr, Mr. Karl Howell  Masculino  26.0
890                                Dooley, Mr. Patrick  Masculino  32.0

     Familiares           Tiquete  Tarifa Cabina Embarcado
0             0         A/5 21171    7.25    NaN         S
1             0          PC 17599   71.28    C85         C
2             0  STON/O2. 3101282    7.93    NaN         S
3             0            113803   53.10   C123         S
4             0            373450    8.05    NaN         S
..          ...               ...     ...    ...       ...
886           0            211536   13.00    NaN         S
887           0            112053   30.00    B42         S
888           2        W./C. 6607   23.45    NaN         S
889           0            111369   30.00   C148         C
890           0            370376    7.75    NaN         Q

[891 rows x 12 columns]]

### Lectura desde URL

Una URL (Uniform Resource Locator o Localizador Uniforme de Recursos) es la dirección única y específica que se utiliza para encontrar cualquier recurso en Internet, como páginas web, imágenes o documentos. Funciona como una dirección postal digital, indicando al navegador el protocolo (ej. https) y la ubicación exacta del archivo.

In [16]:
import requests

# Obtener la página con un User-Agent válido
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'}
response = requests.get("https://es.wikipedia.org/wiki/Municipio_de_Sahuayo", headers=headers)

# Extraer tablas del HTML
tablas = pd.read_html(response.text)

df1 = tablas[0]
print(df1)

          Municipio de Sahuayo  \
0                    Municipio
1       Panorámica de Sahuayo.
2                       Escudo
3                          NaN
4                  Coordenadas
5           Cabecera municipal
6                      Entidad
7                       • País
8                     • Estado
9         Presidente municipal
10          Eventos históricos
11                 • Fundación
12                  Superficie
13                     • Total
14                     Altitud
15                     • Media
16            Población (2020)
17                     • Total
18                  • Densidad
19                  IDH (2020)
20                Huso horario
21                  Clave Lada
22                Código INEGI
23           Sitio web oficial
24  [editar datos en Wikidata]

                               Municipio de Sahuayo.1  \
0                                           Municipio
1                              Panorámica de Sahuayo.
2                                              Escudo
3                                                 NaN
4   20°03′27″N 102°43′26″O﻿ / ﻿20.0575, -102.72388...
5                                  Sahuayo de Morelos
6                                           Municipio
7                                              México
8                                           Michoacán
9                   Manuel Gálvez Sánchez (2024-2027)
10                                                NaN
11  10 de diciembre de 1831 (María Fernanda Gálvez...
12                                                NaN
13                                         128.48 km²
14                                                NaN
15                                    1561 m s. n. m.
16                                                NaN
17                                        78 477 hab.
18                                     612,6 hab./km²
19                                  0.691[1]​ – Medio
20                                              UTC−6
21                                            353[2]​
22                                      16076[3]​[4]​
23                                  Sitio web oficial
24                         [editar datos en Wikidata]

                               Municipio de Sahuayo.2
0                                           Municipio
1                              Panorámica de Sahuayo.
2                                              Escudo
3                                                 NaN
4   20°03′27″N 102°43′26″O﻿ / ﻿20.0575, -102.72388...
5                                  Sahuayo de Morelos
6                                           Municipio
7                                              México
8                                           Michoacán
9                   Manuel Gálvez Sánchez (2024-2027)
10                                                NaN
11  10 de diciembre de 1831 (María Fernanda Gálvez...
12                                                NaN
13                                         128.48 km²
14                                                NaN
15                                    1561 m s. n. m.
16                                                NaN
17                                        78 477 hab.
18                                     612,6 hab./km²
19                                  0.691[1]​ – Medio
20                                              UTC−6
21                                            353[2]​
22                                      16076[3]​[4]​
23                                  Sitio web oficial
24                         [editar datos en Wikidata]

C:\Users\jorge\AppData\Local\Temp\ipykernel_20816\259054673.py:8: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tablas = pd.read_html(response.text)

In [17]:
df2 = tablas[1]
print(df2)

                                                   0
0  Gráfica de evolución demográfica de Municipio ...
1  Fuente: Instituto Nacional de Estadística Geog...

### Leer archivos json

JSON (JavaScript Object Notation) es un formato de texto ligero y estándar para el almacenamiento e intercambio de datos, diseñado para ser fácil de leer tanto por personas como por máquinas. Se utiliza comúnmente en aplicaciones web para transmitir información estructurada entre un servidor y un cliente, destacando por ser independiente del lenguaje de programación.

In [18]:
# Leer archivo JSON
df = pd.read_json('MOCK_DATA.json')

print(df)

    id  first_name    last_name                       email      gender  \
0    1       Chick    Streeting        cstreeting0@ehow.com        Male
1    2     Rodrick   Zavattiero  rzavattiero1@hostgator.com    Bigender
2    3     Emiline        Heild           eheild2@fotki.com      Female
3    4       Bondy       Schall      bschall3@indiegogo.com  Polygender
4    5    Claudina        Jarad         cjarad4@godaddy.com      Female
5    6       Ernie       Easdon             eeasdon5@pen.io        Male
6    7        Alex      Yarwood    ayarwood6@craigslist.org        Male
7    8       Orran  Andrioletti   oandrioletti7@foxnews.com        Male
8    9    Florance      Mangion          fmangion8@ucla.edu      Female
9   10      Sutton      Willmot      swillmot9@so-net.ne.jp        Male
10  11  Anna-diana   Czajkowska     aczajkowskaa@hao123.com      Female
11  12    Claudine     Petracek    cpetracekb@posterous.com  Polygender
12  13          Ax      Shurman         ashurmanc@google.de        Male
13  14         Dav      Paggitt  dpaggittd@seattletimes.com        Male
14  15     Hedwiga         Boag          hboage@skyrock.com      Female
15  16    Elsworth      Hilliam       ehilliamf@yahoo.co.jp        Male
16  17        Olva        Bolan         obolang@arizona.edu      Female
17  18   Sanderson       Lawles          slawlesh@umich.edu        Male
18  19      Wittie      Canadas  wcanadasi@businesswire.com        Male
19  20     Aveline       Hairon        ahaironj@youtube.com      Female

         ip_address
0     77.202.160.10
1    244.19.222.131
2     166.130.36.23
3   218.199.240.125
4    230.161.32.147
5     62.234.126.39
6    114.190.68.104
7     239.68.40.151
8   169.101.200.248
9      162.25.64.98
10   180.50.113.114
11    12.173.156.45
12   55.126.149.143
13  131.114.122.158
14    207.78.180.79
15  117.192.147.138
16      23.51.86.44
17    35.138.205.26
18      27.77.223.3
19    12.64.141.194

### Lectura bases de datos

Las bases de datos SQL son sistemas de gestión de bases de datos relacionales (RDBMS) que organizan los datos en tablas estructuradas con filas y columnas. Utilizan el Lenguaje de Consulta Estructurado (SQL) para crear, consultar, actualizar y gestionar datos, enfocándose en la integridad relacional y la precisión. Son ideales para transacciones complejas.

In [19]:
# importar paquete sqlite3
import sqlite3

conex_sql = sqlite3.connect("festivos_colombia.db")    # Conexion con base de datos
df = pd.read_sql("SELECT * FROM holidays", con=conex_sql)
print(df)

    index        date                                    localName  \
0       0  2019-01-01                                    Año Nuevo
1       1  2019-01-06                       Día de los Reyes Magos
2       2  2019-03-19                              Día de San José
3       3  2019-05-01                              Primero de Mayo
4       4  2019-06-29                        San Pedro y San Pablo
5       5  2019-07-20  Declaracion de la Independencia de Colombia
6       6  2019-08-07                             Battle of Boyacá
7       7  2019-08-15                                  La Asunción
8       8  2019-10-12                               Día de la Raza
9       9  2019-11-01                            Dia de los Santos
10     10  2019-11-11                   Independencia de Cartagena
11     11  2019-12-08                     La Inmaculada Concepción
12     12  2019-12-25                                      Navidad
13     13  2020-01-01                                    Año Nuevo
14     14  2020-01-06                       Día de los Reyes Magos
15     15  2020-03-19                              Día de San José
16     16  2020-05-01                              Primero de Mayo
17     17  2020-06-29                        San Pedro y San Pablo
18     18  2020-07-20  Declaracion de la Independencia de Colombia
19     19  2020-08-07                             Battle of Boyacá
20     20  2020-08-15                                  La Asunción
21     21  2020-10-12                               Día de la Raza
22     22  2020-11-01                            Dia de los Santos
23     23  2020-11-11                   Independencia de Cartagena
24     24  2020-12-08                     La Inmaculada Concepción
25     25  2020-12-25                                      Navidad
26     26  2021-01-01                                    Año Nuevo
27     27  2021-01-06                       Día de los Reyes Magos
28     28  2021-03-19                              Día de San José
29     29  2021-05-01                              Primero de Mayo
30     30  2021-06-29                        San Pedro y San Pablo
31     31  2021-07-20  Declaracion de la Independencia de Colombia
32     32  2021-08-07                             Battle of Boyacá
33     33  2021-08-15                                  La Asunción
34     34  2021-10-12                               Día de la Raza
35     35  2021-11-01                            Dia de los Santos
36     36  2021-11-11                   Independencia de Cartagena
37     37  2021-12-08                     La Inmaculada Concepción
38     38  2021-12-25                                      Navidad

                           name countryCode fixed
0                New Year's Day          CO  TRUE
1                      Epiphany          CO  TRUE
2            Saint Joseph's Day          CO  TRUE
3                    Labour Day          CO  TRUE
4    Saint Peter and Saint Paul          CO  TRUE
5   Declaration of Independence          CO  TRUE
6              Battle of Boyacá          CO  TRUE
7            Assumption of Mary          CO  TRUE
8                  Columbus Day          CO  TRUE
9               All Saints’ Day          CO  TRUE
10    Independence of Cartagena          CO  TRUE
11        Immaculate Conception          CO  TRUE
12                Christmas Day          CO  TRUE
13               New Year's Day          CO  TRUE
14                     Epiphany          CO  TRUE
15           Saint Joseph's Day          CO  TRUE
16                   Labour Day          CO  TRUE
17   Saint Peter and Saint Paul          CO  TRUE
18  Declaration of Independence          CO  TRUE
19             Battle of Boyacá          CO  TRUE
20           Assumption of Mary          CO  TRUE
21                 Columbus Day          CO  TRUE
22              All Saints’ Day          CO  TRUE
23    Independence of Cartagena          CO  TRUE
24        Immaculate Conception          CO  TRUE
25                Christmas Day          CO  TRUE
26               New Year's Day          CO  TRUE
27                     Epiphany          CO  TRUE
28           Saint Joseph's Day          CO  TRUE
29                   Labour Day          CO  TRUE
30   Saint Peter and Saint Paul          CO  TRUE
31  Declaration of Independence          CO  TRUE
32             Battle of Boyacá          CO  TRUE
33           Assumption of Mary          CO  TRUE
34                 Columbus Day          CO  TRUE
35              All Saints’ Day          CO  TRUE
36    Independence of Cartagena          CO  TRUE
37        Immaculate Conception          CO  TRUE
38                Christmas Day          CO  TRUE

In [20]:
# Para leer las fechas en formato date se usa lo siguiente
conex_sql = sqlite3.connect("festivos_colombia.db")    # Conexion con base de datos
df = pd.read_sql(
    "SELECT * FROM holidays",   # Nombre del archivo
    con=conex_sql,              # Base de datos
    parse_dates= "date"         # Columna con las fechas
)
print(df)

    index       date                                    localName  \
0       0 2019-01-01                                    Año Nuevo
1       1 2019-01-06                       Día de los Reyes Magos
2       2 2019-03-19                              Día de San José
3       3 2019-05-01                              Primero de Mayo
4       4 2019-06-29                        San Pedro y San Pablo
5       5 2019-07-20  Declaracion de la Independencia de Colombia
6       6 2019-08-07                             Battle of Boyacá
7       7 2019-08-15                                  La Asunción
8       8 2019-10-12                               Día de la Raza
9       9 2019-11-01                            Dia de los Santos
10     10 2019-11-11                   Independencia de Cartagena
11     11 2019-12-08                     La Inmaculada Concepción
12     12 2019-12-25                                      Navidad
13     13 2020-01-01                                    Año Nuevo
14     14 2020-01-06                       Día de los Reyes Magos
15     15 2020-03-19                              Día de San José
16     16 2020-05-01                              Primero de Mayo
17     17 2020-06-29                        San Pedro y San Pablo
18     18 2020-07-20  Declaracion de la Independencia de Colombia
19     19 2020-08-07                             Battle of Boyacá
20     20 2020-08-15                                  La Asunción
21     21 2020-10-12                               Día de la Raza
22     22 2020-11-01                            Dia de los Santos
23     23 2020-11-11                   Independencia de Cartagena
24     24 2020-12-08                     La Inmaculada Concepción
25     25 2020-12-25                                      Navidad
26     26 2021-01-01                                    Año Nuevo
27     27 2021-01-06                       Día de los Reyes Magos
28     28 2021-03-19                              Día de San José
29     29 2021-05-01                              Primero de Mayo
30     30 2021-06-29                        San Pedro y San Pablo
31     31 2021-07-20  Declaracion de la Independencia de Colombia
32     32 2021-08-07                             Battle of Boyacá
33     33 2021-08-15                                  La Asunción
34     34 2021-10-12                               Día de la Raza
35     35 2021-11-01                            Dia de los Santos
36     36 2021-11-11                   Independencia de Cartagena
37     37 2021-12-08                     La Inmaculada Concepción
38     38 2021-12-25                                      Navidad

                           name countryCode fixed
0                New Year's Day          CO  TRUE
1                      Epiphany          CO  TRUE
2            Saint Joseph's Day          CO  TRUE
3                    Labour Day          CO  TRUE
4    Saint Peter and Saint Paul          CO  TRUE
5   Declaration of Independence          CO  TRUE
6              Battle of Boyacá          CO  TRUE
7            Assumption of Mary          CO  TRUE
8                  Columbus Day          CO  TRUE
9               All Saints’ Day          CO  TRUE
10    Independence of Cartagena          CO  TRUE
11        Immaculate Conception          CO  TRUE
12                Christmas Day          CO  TRUE
13               New Year's Day          CO  TRUE
14                     Epiphany          CO  TRUE
15           Saint Joseph's Day          CO  TRUE
16                   Labour Day          CO  TRUE
17   Saint Peter and Saint Paul          CO  TRUE
18  Declaration of Independence          CO  TRUE
19             Battle of Boyacá          CO  TRUE
20           Assumption of Mary          CO  TRUE
21                 Columbus Day          CO  TRUE
22              All Saints’ Day          CO  TRUE
23    Independence of Cartagena          CO  TRUE
24        Immaculate Conception          CO  TRUE
25                Christmas Day          CO  TRUE
26               New Year's Day          CO  TRUE
27                     Epiphany          CO  TRUE
28           Saint Joseph's Day          CO  TRUE
29                   Labour Day          CO  TRUE
30   Saint Peter and Saint Paul          CO  TRUE
31  Declaration of Independence          CO  TRUE
32             Battle of Boyacá          CO  TRUE
33           Assumption of Mary          CO  TRUE
34                 Columbus Day          CO  TRUE
35              All Saints’ Day          CO  TRUE
36    Independence of Cartagena          CO  TRUE
37        Immaculate Conception          CO  TRUE
38                Christmas Day          CO  TRUE

### Datasets de Kaggle

In [21]:
!pip install kagglehub

Requirement already satisfied: kagglehub in c:\users\jorge\anaconda3\lib\site-packages (1.0.0)
Requirement already satisfied: kagglesdk<1.0,>=0.1.14 in c:\users\jorge\anaconda3\lib\site-packages (from kagglehub) (0.1.16)
Requirement already satisfied: packaging in c:\users\jorge\anaconda3\lib\site-packages (from kagglehub) (25.0)
Requirement already satisfied: pyyaml in c:\users\jorge\anaconda3\lib\site-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in c:\users\jorge\anaconda3\lib\site-packages (from kagglehub) (2.32.5)
Requirement already satisfied: tqdm in c:\users\jorge\anaconda3\lib\site-packages (from kagglehub) (4.67.1)
Requirement already satisfied: protobuf in c:\users\jorge\anaconda3\lib\site-packages (from kagglesdk<1.0,>=0.1.14->kagglehub) (5.29.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\jorge\anaconda3\lib\site-packages (from requests->kagglehub) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\jorge\anaconda3\lib\site-packages (from requests->kagglehub) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\jorge\anaconda3\lib\site-packages (from requests->kagglehub) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\jorge\anaconda3\lib\site-packages (from requests->kagglehub) (2025.11.12)
Requirement already satisfied: colorama in c:\users\jorge\anaconda3\lib\site-packages (from tqdm->kagglehub) (0.4.6)

In [22]:
import kagglehub
import os

# Descargar dataset
path = kagglehub.dataset_download("zkskhurram/world-vs-asia-fuel-prices")
print(path)

# Listar archivos
files = os.listdir(path)
print("Archivos encontrados:", files)

# Leer el primer archivo CSV que encuentres
for file in files:
    if file.endswith('.csv'):
        file_path = os.path.join(path, file)
        print(file_path)  # Imprimir el nombre del file
        print(f"\nLeyendo: {file}")
        df = pd.read_csv(file_path)
        print(df.head())
        break  # Solo lee el primero

C:\Users\jorge\.cache\kagglehub\datasets\zkskhurram\world-vs-asia-fuel-prices\versions\2
Archivos encontrados: ['asia_fuel_prices_detailed.csv', 'asia_subsidy_tracker.csv', 'crude_oil_annual.csv', 'fuel_tax_comparison.csv', 'global_fuel_prices.csv', 'price_trend_monthly.csv']
C:\Users\jorge\.cache\kagglehub\datasets\zkskhurram\world-vs-asia-fuel-prices\versions\2\asia_fuel_prices_detailed.csv

Leyendo: asia_fuel_prices_detailed.csv
      country  sub_region iso3  gasoline_usd_per_liter  diesel_usd_per_liter  \
0    Pakistan  South Asia  PAK                    1.64                  1.86
1       India  South Asia  IND                    1.11                  1.03
2  Bangladesh  South Asia  BGD                    1.07                  0.93
3   Sri Lanka  South Asia  LKA                    1.34                  1.19
4       Nepal  South Asia  NPL                    1.34                  1.21

   lpg_usd_per_kg  avg_monthly_income_usd  fuel_affordability_index  \
0            1.25                     180                       3.7
1            1.08                     280                       8.4
2            0.98                     160                       5.0
3            1.18                     210                       5.2
4            1.28                     120                       3.0

   oil_import_dependency_pct  refinery_capacity_kbpd  ev_adoption_pct  \
0                         85                     450              0.4
1                         85                    5340              2.4
2                        100                      33              0.1
3                        100                      50              0.2
4                        100                       0              0.6

   fuel_subsidy_active  subsidy_cost_bn_usd  co2_transport_mt  price_date  \
0                 True                  5.2              42.5  2026-04-04
1                 True                  8.5             325.0  2026-04-04
2                 True                  2.8              16.2  2026-04-04
3                False                  0.0               8.5  2026-04-04
4                False                  0.0               4.3  2026-04-04

   gasoline_pct_daily_wage
0                     27.3
1                     11.9
2                     20.1
3                     19.1
4                     33.5

## <font color = darkblue> Exploración y limpieza

La exploración y limpieza de datos con Pandas es una etapa fundamental en la ciencia de datos para garantizar que los conjuntos de datos sean precisos, consistentes y estén listos para el análisis o modelado. Pandas ofrece estructuras de datos rápidas y flexibles, siendo la más utilizada el DataFrame.

### shape

El atributo .shape en Pandas devuelve una tupla que representa las dimensiones de un DataFrame o Series, indicando el número de filas y columnas (filas, columnas). Es un atributo, no un método, por lo que se utiliza sin paréntesis (df.shape) para obtener rápidamente la estructura de los datos.

In [85]:
# Vamos a usar el dataset titanic
df_titanic = pd.read_csv(
    "titanic.csv",
    header=0,
    sep = ";"
)

df_titanic.shape

(891, 11)

### head

El método .head() en pandas es una función utilizada para visualizar rápidamente las primeras *n* filas de un DataFrame o Serie. Por defecto, muestra las primeras 5 filas, siendo ideal para verificar la estructura, nombres de columnas y tipos de datos sin imprimir todo el conjunto de datos.

In [23]:
# Mostrar las primeras 5 filas
df_titanic.head()

,Id_Pasajero,Survived,Clase,Nombre,Sexo,Edad,Familiares,Tiquete,Tarifa,Cabina,Embarcado
0,1,0,3,"Braund, Mr. Owen Harris",Masculino,22.0,0,A/5 21171,7.25,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Femenino,38.0,0,PC 17599,71.28,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",Femenino,26.0,0,STON/O2. 3101282,7.93,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Femenino,35.0,0,113803,53.10,C123,S
4,5,0,3,"Allen, Mr. William Henry",Masculino,35.0,0,373450,8.05,NaN,S

In [24]:
# Mostrar las primeras 10 filas
df_titanic.head(10)

,Id_Pasajero,Survived,Clase,Nombre,Sexo,Edad,Familiares,Tiquete,Tarifa,Cabina,Embarcado
0,1,0,3,"Braund, Mr. Owen Harris",Masculino,22.0,0,A/5 21171,7.25,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Femenino,38.0,0,PC 17599,71.28,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",Femenino,26.0,0,STON/O2. 3101282,7.93,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Femenino,35.0,0,113803,53.10,C123,S
4,5,0,3,"Allen, Mr. William Henry",Masculino,35.0,0,373450,8.05,NaN,S
5,6,0,3,"Moran, Mr. James",Masculino,NaN,0,330877,8.46,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",Masculino,54.0,0,17463,51.86,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",Masculino,2.0,1,349909,21.08,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",Femenino,27.0,2,347742,11.13,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",Femenino,14.0,0,237736,30.07,NaN,C

### tail

El método tail() en pandas se utiliza para visualizar rápidamente las últimas *n* filas de un DataFrame o Serie. Por defecto, muestra las últimas 5 filas, pero se puede personalizar pasando un número entero como argumento (ej. df.tail(10)). Es una herramienta fundamental para explorar datos, verificar cargas o confirmar ordenamientos.

In [25]:
# Mostrar las ultimas 5 filas
df_titanic.tail()

,Id_Pasajero,Survived,Clase,Nombre,Sexo,Edad,Familiares,Tiquete,Tarifa,Cabina,Embarcado
886,887,0,2,"Montvila, Rev. Juozas",Masculino,27.0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",Femenino,19.0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",Femenino,NaN,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",Masculino,26.0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",Masculino,32.0,0,370376,7.75,NaN,Q

In [26]:
# Mostrar las ultimas 10 filas
df_titanic.tail(10)

,Id_Pasajero,Survived,Clase,Nombre,Sexo,Edad,Familiares,Tiquete,Tarifa,Cabina,Embarcado
881,882,0,3,"Markun, Mr. Johann",Masculino,33.0,0,349257,7.90,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",Femenino,22.0,0,7552,10.52,NaN,S
883,884,0,2,"Banfield, Mr. Frederick James",Masculino,28.0,0,C.A./SOTON 34068,10.50,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",Masculino,25.0,0,SOTON/OQ 392076,7.05,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",Femenino,39.0,5,382652,29.13,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",Masculino,27.0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",Femenino,19.0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",Femenino,NaN,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",Masculino,26.0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",Masculino,32.0,0,370376,7.75,NaN,Q

### info

El método .info() en Pandas es una función fundamental utilizada para obtener un resumen conciso y estructural de un DataFrame. Proporciona una visión rápida del número de filas, nombres de columnas, tipos de datos (dtypes), valores no nulos y el uso total de memoria, siendo esencial para la limpieza y exploración inicial de datos.

In [27]:
# Obtener informacion del dataset titanic
df_titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Id_Pasajero  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Clase        891 non-null    int64
 3   Nombre       891 non-null    object
 4   Sexo         891 non-null    object
 5   Edad         714 non-null    float64
 6   Familiares   891 non-null    int64
 7   Tiquete      891 non-null    object
 8   Tarifa       891 non-null    float64
 9   Cabina       204 non-null    object
 10  Embarcado    889 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 76.7+ KB

### describe

El método describe() en Pandas es una función fundamental para el análisis exploratorio de datos (EDA) que genera un resumen estadístico rápido de un DataFrame o Serie. Calcula automáticamente métricas clave como el conteo, media, desviación estándar, valores mínimos/máximos y percentiles (25,50,75), ignorando valores nulos (NaN).

In [28]:
df_titanic.describe()

       Id_Pasajero    Survived       Clase        Edad  Familiares      Tarifa
count   891.000000  891.000000  891.000000  714.000000  891.000000  891.000000
mean    446.000000    0.383838    2.308642   29.699118    0.381594   32.205017
std     257.353842    0.486592    0.836071   14.526497    0.806057   49.693389
min       1.000000    0.000000    1.000000    0.420000    0.000000    0.000000
25%     223.500000    0.000000    2.000000   20.125000    0.000000    7.915000
50%     446.000000    0.000000    3.000000   28.000000    0.000000   14.450000
75%     668.500000    1.000000    3.000000   38.000000    0.000000   31.000000
max     891.000000    1.000000    3.000000   80.000000    6.000000  512.330000

### dtypes

dtypes en pandas es un atributo de DataFrame que devuelve una serie indicando el tipo de dato subyacente (entero, flotante, objeto/texto, etc.) de cada columna. Permite identificar cómo están almacenados los datos para optimizar la memoria y asegurar que las operaciones (como sumas o fechas) sean correctas.

In [29]:
df_titanic.dtypes

Id_Pasajero      int64
Survived         int64
Clase            int64
Nombre          object
Sexo            object
Edad           float64
Familiares       int64
Tiquete         object
Tarifa         float64
Cabina          object
Embarcado       object
dtype: object

### isnull 

isnull() en pandas es un método utilizado para detectar valores faltantes (NaN, None, NaT) en un DataFrame o Series. Devuelve un objeto del mismo tamaño con valores booleanos (True si es nulo, False si no). Es un alias de isna(), por lo que funcionan exactamente igual para identificar datos faltantes.

In [30]:
# Detectar los valores nulos en titanic
df_titanic.isnull()

,Id_Pasajero,Survived,Clase,Nombre,Sexo,Edad,Familiares,Tiquete,Tarifa,Cabina,Embarcado
0,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,True,False
887,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,False,False,True,False,False,False,True,False
889,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,True,False

In [31]:
# Sumar los valores nulos de cada columna
df_titanic.isnull().sum()

Id_Pasajero      0
Survived         0
Clase            0
Nombre           0
Sexo             0
Edad           177
Familiares       0
Tiquete          0
Tarifa           0
Cabina         687
Embarcado        2
dtype: int64

### dropna

dropna() en pandas es un método esencial para la limpieza de datos que elimina filas o columnas que contienen valores faltantes (NaN o None). Por defecto, elimina cualquier fila con al menos un valor nulo, permitiendo limpiar conjuntos de datos incompletos para su análisis.

In [32]:
# Hacer una copia del dataset del titanic
df_titanic_copy_1 = df_titanic.copy()
df_titanic_copy_2 = df_titanic.copy()
df_titanic_copy_3 = df_titanic.copy()
df_titanic_copy_4 = df_titanic.copy()
df_titanic_copy_5 = df_titanic.copy()

# Eliminar todos los registros con datos nulos
df_titanic_copy_1.dropna()

,Id_Pasajero,Survived,Clase,Nombre,Sexo,Edad,Familiares,Tiquete,Tarifa,Cabina,Embarcado
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Femenino,38.0,0,PC 17599,71.28,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Femenino,35.0,0,113803,53.10,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",Masculino,54.0,0,17463,51.86,E46,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",Femenino,4.0,1,PP 9549,16.70,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",Femenino,58.0,0,113783,26.55,C103,S
...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",Femenino,47.0,1,11751,52.55,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",Masculino,33.0,0,695,5.00,B51 B53 B55,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",Femenino,56.0,1,11767,83.16,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",Femenino,19.0,0,112053,30.00,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",Masculino,26.0,0,111369,30.00,C148,C

In [33]:
# Eliminar por filas
df_titanic_copy_2.dropna(axis = 0)

,Id_Pasajero,Survived,Clase,Nombre,Sexo,Edad,Familiares,Tiquete,Tarifa,Cabina,Embarcado
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Femenino,38.0,0,PC 17599,71.28,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Femenino,35.0,0,113803,53.10,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",Masculino,54.0,0,17463,51.86,E46,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",Femenino,4.0,1,PP 9549,16.70,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",Femenino,58.0,0,113783,26.55,C103,S
...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",Femenino,47.0,1,11751,52.55,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",Masculino,33.0,0,695,5.00,B51 B53 B55,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",Femenino,56.0,1,11767,83.16,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",Femenino,19.0,0,112053,30.00,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",Masculino,26.0,0,111369,30.00,C148,C

In [34]:
# Eliminar por columnas
df_titanic_copy_3.dropna(axis = 1)

,Id_Pasajero,Survived,Clase,Nombre,Sexo,Familiares,Tiquete,Tarifa
0,1,0,3,"Braund, Mr. Owen Harris",Masculino,0,A/5 21171,7.25
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Femenino,0,PC 17599,71.28
2,3,1,3,"Heikkinen, Miss. Laina",Femenino,0,STON/O2. 3101282,7.93
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Femenino,0,113803,53.10
4,5,0,3,"Allen, Mr. William Henry",Masculino,0,373450,8.05
...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",Masculino,0,211536,13.00
887,888,1,1,"Graham, Miss. Margaret Edith",Femenino,0,112053,30.00
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",Femenino,2,W./C. 6607,23.45
889,890,1,1,"Behr, Mr. Karl Howell",Masculino,0,111369,30.00
890,891,0,3,"Dooley, Mr. Patrick",Masculino,0,370376,7.75

In [35]:
# Eliminar por columna [tiquete, embarcado]
df_titanic_copy_4.dropna(subset=["Tiquete","Embarcado"])

,Id_Pasajero,Survived,Clase,Nombre,Sexo,Edad,Familiares,Tiquete,Tarifa,Cabina,Embarcado
0,1,0,3,"Braund, Mr. Owen Harris",Masculino,22.0,0,A/5 21171,7.25,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Femenino,38.0,0,PC 17599,71.28,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",Femenino,26.0,0,STON/O2. 3101282,7.93,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Femenino,35.0,0,113803,53.10,C123,S
4,5,0,3,"Allen, Mr. William Henry",Masculino,35.0,0,373450,8.05,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",Masculino,27.0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",Femenino,19.0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",Femenino,NaN,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",Masculino,26.0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",Masculino,32.0,0,370376,7.75,NaN,Q

### fillna

El método fillna() de pandas se utiliza para rellenar, reemplazar o imputar valores faltantes (NaN o None) en DataFrames o Series con valores específicos, la media, mediana o métodos de propagación (ffill/bfill). Es una herramienta esencial en la limpieza de datos, permitiendo manejar datos nulos de manera eficiente sin borrarlos.

In [41]:
# Hacer una copia del dataset del titanic
df_titanic_copy_1 = df_titanic.copy()
df_titanic_copy_2 = df_titanic.copy()
df_titanic_copy_3 = df_titanic.copy()
df_titanic_copy_4 = df_titanic.copy()
df_titanic_copy_5 = df_titanic.copy()

In [42]:
# Rellenar valores faltantes con ceros
df_titanic_copy_1.fillna(0)

,Id_Pasajero,Survived,Clase,Nombre,Sexo,Edad,Familiares,Tiquete,Tarifa,Cabina,Embarcado
0,1,0,3,"Braund, Mr. Owen Harris",Masculino,22.0,0,A/5 21171,7.25,0,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Femenino,38.0,0,PC 17599,71.28,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",Femenino,26.0,0,STON/O2. 3101282,7.93,0,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Femenino,35.0,0,113803,53.10,C123,S
4,5,0,3,"Allen, Mr. William Henry",Masculino,35.0,0,373450,8.05,0,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",Masculino,27.0,0,211536,13.00,0,S
887,888,1,1,"Graham, Miss. Margaret Edith",Femenino,19.0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",Femenino,0.0,2,W./C. 6607,23.45,0,S
889,890,1,1,"Behr, Mr. Karl Howell",Masculino,26.0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",Masculino,32.0,0,370376,7.75,0,Q

In [43]:
# Rellenar columnas con diferentes valores
df_titanic_copy_2.fillna({'Edad': 20, 'Cabina': "N"})  # Columna Edad con 20; columna Cabina con N

,Id_Pasajero,Survived,Clase,Nombre,Sexo,Edad,Familiares,Tiquete,Tarifa,Cabina,Embarcado
0,1,0,3,"Braund, Mr. Owen Harris",Masculino,22.0,0,A/5 21171,7.25,N,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Femenino,38.0,0,PC 17599,71.28,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",Femenino,26.0,0,STON/O2. 3101282,7.93,N,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Femenino,35.0,0,113803,53.10,C123,S
4,5,0,3,"Allen, Mr. William Henry",Masculino,35.0,0,373450,8.05,N,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",Masculino,27.0,0,211536,13.00,N,S
887,888,1,1,"Graham, Miss. Margaret Edith",Femenino,19.0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",Femenino,20.0,2,W./C. 6607,23.45,N,S
889,890,1,1,"Behr, Mr. Karl Howell",Masculino,26.0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",Masculino,32.0,0,370376,7.75,N,Q

In [46]:
df_titanic_copy_3.fillna(method='ffill')  # Usa el último valor válido

C:\Users\jorge\AppData\Local\Temp\ipykernel_20816\1399476442.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_titanic_copy_3.fillna(method='ffill')  # Usa el último valor válido

,Id_Pasajero,Survived,Clase,Nombre,Sexo,Edad,Familiares,Tiquete,Tarifa,Cabina,Embarcado
0,1,0,3,"Braund, Mr. Owen Harris",Masculino,22.0,0,A/5 21171,7.25,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Femenino,38.0,0,PC 17599,71.28,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",Femenino,26.0,0,STON/O2. 3101282,7.93,C85,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Femenino,35.0,0,113803,53.10,C123,S
4,5,0,3,"Allen, Mr. William Henry",Masculino,35.0,0,373450,8.05,C123,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",Masculino,27.0,0,211536,13.00,C50,S
887,888,1,1,"Graham, Miss. Margaret Edith",Femenino,19.0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",Femenino,19.0,2,W./C. 6607,23.45,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",Masculino,26.0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",Masculino,32.0,0,370376,7.75,C148,Q

In [49]:
df_titanic_copy_4.fillna(method='bfill')  # Usa el siguiente valor válido

C:\Users\jorge\AppData\Local\Temp\ipykernel_20816\3736289129.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_titanic_copy_4.fillna(method='bfill')  # Usa el siguiente valor válido

,Id_Pasajero,Survived,Clase,Nombre,Sexo,Edad,Familiares,Tiquete,Tarifa,Cabina,Embarcado
0,1,0,3,"Braund, Mr. Owen Harris",Masculino,22.0,0,A/5 21171,7.25,C85,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Femenino,38.0,0,PC 17599,71.28,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",Femenino,26.0,0,STON/O2. 3101282,7.93,C123,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Femenino,35.0,0,113803,53.10,C123,S
4,5,0,3,"Allen, Mr. William Henry",Masculino,35.0,0,373450,8.05,E46,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",Masculino,27.0,0,211536,13.00,B42,S
887,888,1,1,"Graham, Miss. Margaret Edith",Femenino,19.0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",Femenino,26.0,2,W./C. 6607,23.45,C148,S
889,890,1,1,"Behr, Mr. Karl Howell",Masculino,26.0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",Masculino,32.0,0,370376,7.75,NaN,Q

In [65]:
# Crear un dataframe con NaNs
import numpy as np
import random

# Fijar semilla para reproducibilidad
np.random.seed(42)

# Crear DataFrame con 50 registros y valores NaN aleatorios
df = pd.DataFrame({
    'edad': np.random.randint(18, 65, 50).astype(float),
    'salario': np.random.randint(20000, 80000, 50).astype(float),
    'altura': np.random.uniform(1.50, 1.90, 50),
    'puntuacion': np.random.randint(1, 10, 50).astype(float)
})

# Insertar NaN aleatoriamente (aprox 10-15% de datos faltantes)
for col in df.columns:
    mask = np.random.random(50) < 0.12  # 12% NaN
    df.loc[mask, col] = np.nan

In [66]:
# Crear copias para cada método
df_copy_1 = df.copy()
df_copy_2 = df.copy()
df_copy_3 = df.copy()
df_copy_4 = df.copy()

In [67]:
# Con la media
df_copy_1.fillna(df_copy_1.mean())

         edad       salario    altura  puntuacion
0   56.000000  46280.608696  1.556370         4.0
1   46.000000  74638.000000  1.694581         7.0
2   32.000000  43483.000000  1.529820         9.0
3   60.000000  78822.000000  1.894755         4.9
4   25.000000  68555.000000  1.808898         4.9
5   38.000000  79900.000000  1.579486         1.0
6   40.761905  37159.000000  1.502209         9.0
7   36.000000  64974.000000  1.826185         9.0
8   40.000000  60994.000000  1.782743         4.0
9   28.000000  34541.000000  1.791603         9.0
10  40.761905  55920.000000  1.808508         3.0
11  41.000000  46531.000000  1.529618         7.0
12  53.000000  21585.000000  1.643386         6.0
13  40.761905  23943.000000  1.546348         8.0
14  41.000000  46280.608696  1.845241         9.0
15  20.000000  39457.000000  1.749319         5.0
16  39.000000  21021.000000  1.632359         1.0
17  19.000000  31653.000000  1.525423         3.0
18  41.000000  63573.000000  1.624393         8.0
19  61.000000  33417.000000  1.630073         6.0
20  47.000000  72995.000000  1.791842         8.0
21  55.000000  60757.000000  1.755023         9.0
22  19.000000  29692.000000  1.854885         4.0
23  40.761905  65758.000000  1.688886         1.0
24  50.000000  26873.000000  1.547838         4.9
25  29.000000  25675.000000  1.694581         4.9
26  39.000000  20161.000000  1.804314         4.9
27  61.000000  57065.000000  1.694581         4.9
28  42.000000  46557.000000  1.808387         3.0
29  44.000000  46280.608696  1.697518         1.0
30  59.000000  52606.000000  1.709093         5.0
31  45.000000  31534.000000  1.671016         4.9
32  40.761905  49127.000000  1.694581         8.0
33  32.000000  60397.000000  1.694581         1.0
34  64.000000  45851.000000  1.512572         1.0
35  61.000000  21016.000000  1.754564         2.0
36  20.000000  46280.608696  1.625742         2.0
37  54.000000  75591.000000  1.703428         6.0
38  24.000000  44276.000000  1.863027         7.0
39  38.000000  43247.000000  1.599717         4.9
40  26.000000  44300.000000  1.664153         1.0
41  56.000000  28529.000000  1.694581         1.0
42  35.000000  37262.000000  1.694581         3.0
43  40.761905  29268.000000  1.530792         2.0
44  42.000000  41271.000000  1.615901         5.0
45  31.000000  32185.000000  1.564489         6.0
46  26.000000  41243.000000  1.871879         4.9
47  40.761905  59099.000000  1.823248         4.0
48  40.761905  28571.000000  1.753362         4.9
49  37.000000  77836.000000  1.848584         8.0

In [68]:
# Con la mediana
df_copy_2.fillna(df_copy_2.median())

    edad  salario    altura  puntuacion
0   56.0  43879.5  1.556370         4.0
1   46.0  74638.0  1.697518         7.0
2   32.0  43483.0  1.529820         9.0
3   60.0  78822.0  1.894755         5.0
4   25.0  68555.0  1.808898         5.0
5   38.0  79900.0  1.579486         1.0
6   40.5  37159.0  1.502209         9.0
7   36.0  64974.0  1.826185         9.0
8   40.0  60994.0  1.782743         4.0
9   28.0  34541.0  1.791603         9.0
10  40.5  55920.0  1.808508         3.0
11  41.0  46531.0  1.529618         7.0
12  53.0  21585.0  1.643386         6.0
13  40.5  23943.0  1.546348         8.0
14  41.0  43879.5  1.845241         9.0
15  20.0  39457.0  1.749319         5.0
16  39.0  21021.0  1.632359         1.0
17  19.0  31653.0  1.525423         3.0
18  41.0  63573.0  1.624393         8.0
19  61.0  33417.0  1.630073         6.0
20  47.0  72995.0  1.791842         8.0
21  55.0  60757.0  1.755023         9.0
22  19.0  29692.0  1.854885         4.0
23  40.5  65758.0  1.688886         1.0
24  50.0  26873.0  1.547838         5.0
25  29.0  25675.0  1.697518         5.0
26  39.0  20161.0  1.804314         5.0
27  61.0  57065.0  1.697518         5.0
28  42.0  46557.0  1.808387         3.0
29  44.0  43879.5  1.697518         1.0
30  59.0  52606.0  1.709093         5.0
31  45.0  31534.0  1.671016         5.0
32  40.5  49127.0  1.697518         8.0
33  32.0  60397.0  1.697518         1.0
34  64.0  45851.0  1.512572         1.0
35  61.0  21016.0  1.754564         2.0
36  20.0  43879.5  1.625742         2.0
37  54.0  75591.0  1.703428         6.0
38  24.0  44276.0  1.863027         7.0
39  38.0  43247.0  1.599717         5.0
40  26.0  44300.0  1.664153         1.0
41  56.0  28529.0  1.697518         1.0
42  35.0  37262.0  1.697518         3.0
43  40.5  29268.0  1.530792         2.0
44  42.0  41271.0  1.615901         5.0
45  31.0  32185.0  1.564489         6.0
46  26.0  41243.0  1.871879         5.0
47  40.5  59099.0  1.823248         4.0
48  40.5  28571.0  1.753362         5.0
49  37.0  77836.0  1.848584         8.0

### interpolate

El método interpolate() en Pandas es la herramienta principal para rellenar valores faltantes (NaN) estimándolos basándose en los datos existentes, ideal para series temporales o datos ordenados. Su uso básico es df.interpolate(method='linear'), que calcula valores intermedios mediante líneas rectas entre puntos conocidos.

In [74]:
df_copy_3.interpolate(method='linear', inplace=True)
df_copy_3

         edad  salario    altura  puntuacion
0   56.000000      NaN  1.556370    4.000000
1   46.000000  74638.0  1.543095    7.000000
2   32.000000  43483.0  1.529820    9.000000
3   60.000000  78822.0  1.894755    6.333333
4   25.000000  68555.0  1.808898    3.666667
5   38.000000  79900.0  1.579486    1.000000
6   37.000000  37159.0  1.502209    9.000000
7   36.000000  64974.0  1.826185    9.000000
8   40.000000  60994.0  1.782743    4.000000
9   28.000000  34541.0  1.791603    9.000000
10  34.500000  55920.0  1.808508    3.000000
11  41.000000  46531.0  1.529618    7.000000
12  53.000000  21585.0  1.643386    6.000000
13  47.000000  23943.0  1.546348    8.000000
14  41.000000  31700.0  1.845241    9.000000
15  20.000000  39457.0  1.749319    5.000000
16  39.000000  21021.0  1.632359    1.000000
17  19.000000  31653.0  1.525423    3.000000
18  41.000000  63573.0  1.624393    8.000000
19  61.000000  33417.0  1.630073    6.000000
20  47.000000  72995.0  1.791842    8.000000
21  55.000000  60757.0  1.755023    9.000000
22  19.000000  29692.0  1.854885    4.000000
23  34.500000  65758.0  1.688886    1.000000
24  50.000000  26873.0  1.547838    1.400000
25  29.000000  25675.0  1.676076    1.800000
26  39.000000  20161.0  1.804314    2.200000
27  61.000000  57065.0  1.806350    2.600000
28  42.000000  46557.0  1.808387    3.000000
29  44.000000  49581.5  1.697518    1.000000
30  59.000000  52606.0  1.709093    5.000000
31  45.000000  31534.0  1.671016    6.500000
32  38.500000  49127.0  1.618201    8.000000
33  32.000000  60397.0  1.565387    1.000000
34  64.000000  45851.0  1.512572    1.000000
35  61.000000  21016.0  1.754564    2.000000
36  20.000000  48303.5  1.625742    2.000000
37  54.000000  75591.0  1.703428    6.000000
38  24.000000  44276.0  1.863027    7.000000
39  38.000000  43247.0  1.599717    4.000000
40  26.000000  44300.0  1.664153    1.000000
41  56.000000  28529.0  1.619699    1.000000
42  35.000000  37262.0  1.575246    3.000000
43  38.500000  29268.0  1.530792    2.000000
44  42.000000  41271.0  1.615901    5.000000
45  31.000000  32185.0  1.564489    6.000000
46  26.000000  41243.0  1.871879    5.000000
47  29.666667  59099.0  1.823248    4.000000
48  33.333333  28571.0  1.753362    6.000000
49  37.000000  77836.0  1.848584    8.000000

In [75]:
# Interpolate methods 'nearest’, ‘zero’, ‘slinear’, ‘quadratic’, ‘cubic’, ‘barycentric’, ‘polynomial’
df_copy_4.interpolate(method='nearest', inplace=True)
df_copy_4

    edad  salario    altura  puntuacion
0   56.0      NaN  1.556370         4.0
1   46.0  74638.0  1.556370         7.0
2   32.0  43483.0  1.529820         9.0
3   60.0  78822.0  1.894755         9.0
4   25.0  68555.0  1.808898         1.0
5   38.0  79900.0  1.579486         1.0
6   38.0  37159.0  1.502209         9.0
7   36.0  64974.0  1.826185         9.0
8   40.0  60994.0  1.782743         4.0
9   28.0  34541.0  1.791603         9.0
10  28.0  55920.0  1.808508         3.0
11  41.0  46531.0  1.529618         7.0
12  53.0  21585.0  1.643386         6.0
13  53.0  23943.0  1.546348         8.0
14  41.0  23943.0  1.845241         9.0
15  20.0  39457.0  1.749319         5.0
16  39.0  21021.0  1.632359         1.0
17  19.0  31653.0  1.525423         3.0
18  41.0  63573.0  1.624393         8.0
19  61.0  33417.0  1.630073         6.0
20  47.0  72995.0  1.791842         8.0
21  55.0  60757.0  1.755023         9.0
22  19.0  29692.0  1.854885         4.0
23  19.0  65758.0  1.688886         1.0
24  50.0  26873.0  1.547838         1.0
25  29.0  25675.0  1.547838         1.0
26  39.0  20161.0  1.804314         3.0
27  61.0  57065.0  1.804314         3.0
28  42.0  46557.0  1.808387         3.0
29  44.0  46557.0  1.697518         1.0
30  59.0  52606.0  1.709093         5.0
31  45.0  31534.0  1.671016         5.0
32  45.0  49127.0  1.671016         8.0
33  32.0  60397.0  1.512572         1.0
34  64.0  45851.0  1.512572         1.0
35  61.0  21016.0  1.754564         2.0
36  20.0  21016.0  1.625742         2.0
37  54.0  75591.0  1.703428         6.0
38  24.0  44276.0  1.863027         7.0
39  38.0  43247.0  1.599717         7.0
40  26.0  44300.0  1.664153         1.0
41  56.0  28529.0  1.664153         1.0
42  35.0  37262.0  1.530792         3.0
43  35.0  29268.0  1.530792         2.0
44  42.0  41271.0  1.615901         5.0
45  31.0  32185.0  1.564489         6.0
46  26.0  41243.0  1.871879         6.0
47  26.0  59099.0  1.823248         4.0
48  37.0  28571.0  1.753362         4.0
49  37.0  77836.0  1.848584         8.0

### duplicated

El método duplicated() en Pandas (para DataFrames y Series) se utiliza para identificar filas duplicadas. Devuelve una serie booleana (True/False) indicando si cada fila es un duplicado de una anterior. Es esencial para la limpieza de datos antes del análisis, permitiendo localizar o eliminar registros repetidos.

In [79]:
# Crear dataset con 50 registros (incluyendo duplicados)
np.random.seed(42)

datos = {
    'id': list(range(1, 41)) + [5, 12, 18, 25, 30, 35, 38, 42, 45, 48],  # IDs repetidos
    'nombre': ['Ana', 'Carlos', 'Maria', 'Juan', 'Luis', 'Ana', 'Carlos', 'Maria', 'Sofia', 'Pedro'] * 5,
    'edad': [25, 30, 35, 28, 22, 25, 30, 35, 29, 31] * 5,
    'ciudad': ['Madrid', 'Barcelona', 'Madrid', 'Valencia', 'Barcelona', 
               'Madrid', 'Barcelona', 'Madrid', 'Sevilla', 'Bilbao'] * 5,
    'salario': [30000, 35000, 40000, 32000, 28000] * 10
}

df = pd.DataFrame(datos)

In [80]:
# Obtener los valores duplicados
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41     True
42     True
43    False
44    False
45    False
46    False
47    False
48    False
49    False
dtype: bool

In [82]:
# Duplicados por nombre y edad
df.duplicated(subset=["nombre","edad"])

0     False
1     False
2     False
3     False
4     False
5      True
6      True
7      True
8     False
9     False
10     True
11     True
12     True
13     True
14     True
15     True
16     True
17     True
18     True
19     True
20     True
21     True
22     True
23     True
24     True
25     True
26     True
27     True
28     True
29     True
30     True
31     True
32     True
33     True
34     True
35     True
36     True
37     True
38     True
39     True
40     True
41     True
42     True
43     True
44     True
45     True
46     True
47     True
48     True
49     True
dtype: bool

### drop_duplicates

El método drop_duplicates() en Pandas se utiliza para eliminar filas duplicadas de un DataFrame o Series, devolviendo un nuevo objeto sin dichas filas. Por defecto, mantiene la primera aparición (keep='first') y considera todas las columnas, aunque permite especificar subconjuntos (subset) y el comportamiento de eliminación (last, False).

In [83]:
df.drop_duplicates()
df

    id  nombre  edad     ciudad  salario
0    1     Ana    25     Madrid    30000
1    2  Carlos    30  Barcelona    35000
2    3   Maria    35     Madrid    40000
3    4    Juan    28   Valencia    32000
4    5    Luis    22  Barcelona    28000
5    6     Ana    25     Madrid    30000
6    7  Carlos    30  Barcelona    35000
7    8   Maria    35     Madrid    40000
8    9   Sofia    29    Sevilla    32000
9   10   Pedro    31     Bilbao    28000
10  11     Ana    25     Madrid    30000
11  12  Carlos    30  Barcelona    35000
12  13   Maria    35     Madrid    40000
13  14    Juan    28   Valencia    32000
14  15    Luis    22  Barcelona    28000
15  16     Ana    25     Madrid    30000
16  17  Carlos    30  Barcelona    35000
17  18   Maria    35     Madrid    40000
18  19   Sofia    29    Sevilla    32000
19  20   Pedro    31     Bilbao    28000
20  21     Ana    25     Madrid    30000
21  22  Carlos    30  Barcelona    35000
22  23   Maria    35     Madrid    40000
23  24    Juan    28   Valencia    32000
24  25    Luis    22  Barcelona    28000
25  26     Ana    25     Madrid    30000
26  27  Carlos    30  Barcelona    35000
27  28   Maria    35     Madrid    40000
28  29   Sofia    29    Sevilla    32000
29  30   Pedro    31     Bilbao    28000
30  31     Ana    25     Madrid    30000
31  32  Carlos    30  Barcelona    35000
32  33   Maria    35     Madrid    40000
33  34    Juan    28   Valencia    32000
34  35    Luis    22  Barcelona    28000
35  36     Ana    25     Madrid    30000
36  37  Carlos    30  Barcelona    35000
37  38   Maria    35     Madrid    40000
38  39   Sofia    29    Sevilla    32000
39  40   Pedro    31     Bilbao    28000
40   5     Ana    25     Madrid    30000
41  12  Carlos    30  Barcelona    35000
42  18   Maria    35     Madrid    40000
43  25    Juan    28   Valencia    32000
44  30    Luis    22  Barcelona    28000
45  35     Ana    25     Madrid    30000
46  38  Carlos    30  Barcelona    35000
47  42   Maria    35     Madrid    40000
48  45   Sofia    29    Sevilla    32000
49  48   Pedro    31     Bilbao    28000

In [4]:
# Leer la base de datos festivos colombia
# importar paquete sqlite3
import sqlite3

conex_sql = sqlite3.connect("festivos_colombia.db")    # Conexion con base de datos
df_colombia = pd.read_sql("SELECT * FROM holidays", con=conex_sql)
df_colombia.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   index        39 non-null     int64
 1   date         39 non-null     object
 2   localName    39 non-null     object
 3   name         39 non-null     object
 4   countryCode  39 non-null     object
 5   fixed        39 non-null     object
dtypes: int64(1), object(5)
memory usage: 2.0+ KB

In [5]:
# Hacer copias
df_colombia_copy_1 = df_colombia.copy()
df_colombia_copy_2 = df_colombia.copy()

### rename

El método rename() de pandas se utiliza para cambiar los nombres de las columnas o índices en un DataFrame o Series. Se usa principalmente pasando un diccionario al parámetro columns o index (formato {'nombre_antiguo': 'nombre_nuevo'}), permitiendo modificar etiquetas específicas sin alterar los datos

In [6]:
# Obtener el nombre de las columnas
df_colombia_copy_1.columns

Index(['index', 'date', 'localName', 'name', 'countryCode', 'fixed'], dtype='object')

In [7]:
# Cambiar el nombre de las columnas
df_colombia_copy_1.rename(columns = {"index":"indice","date": "fecha","localName":"Localidad","name":"Nombre"},inplace = True)
df_colombia_copy_1.head()

,indice,fecha,Localidad,Nombre,countryCode,fixed
0,0,2019-01-01,Año Nuevo,New Year's Day,CO,TRUE
1,1,2019-01-06,Día de los Reyes Magos,Epiphany,CO,TRUE
2,2,2019-03-19,Día de San José,Saint Joseph's Day,CO,TRUE
3,3,2019-05-01,Primero de Mayo,Labour Day,CO,TRUE
4,4,2019-06-29,San Pedro y San Pablo,Saint Peter and Saint Paul,CO,TRUE

### Cambio de tipo de datos

El cambio de tipos de datos en Pandas se realiza principalmente con el método astype(), que permite convertir columnas a tipos como int, float, str o bool. Para conversiones numéricas más complejas, se usa pd.to_numeric() con el parámetro errors='coerce' para manejar errores. Los cambios se aplican reasignando la columna (df['col'] = df['col'].astype(tipo))

In [108]:
df_colombia_copy_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   index        39 non-null     int64
 1   date         39 non-null     object
 2   localName    39 non-null     object
 3   name         39 non-null     object
 4   countryCode  39 non-null     object
 5   fixed        39 non-null     object
dtypes: int64(1), object(5)
memory usage: 2.0+ KB

In [117]:
# Convertir a entero
df_colombia_copy_2['index'] = df_colombia_copy_2['index'].astype('int32')
df_colombia_copy_2.info()

# Convertir a float
df_colombia_copy_2['index'] = df_colombia_copy_2['index'].astype('float64')
df_colombia_copy_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   index        39 non-null     int32
 1   date         39 non-null     datetime64[ns]
 2   localName    39 non-null     object
 3   name         39 non-null     object
 4   countryCode  39 non-null     object
 5   fixed        39 non-null     object
dtypes: datetime64[ns](1), int32(1), object(4)
memory usage: 1.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   index        39 non-null     float64
 1   date         39 non-null     datetime64[ns]
 2   localName    39 non-null     object
 3   name         39 non-null     object
 4   countryCode  39 non-null     object
 5   fixed        39 non-null     object
dtypes: datetime64[ns](1), float64(1), object(4)
memory usage: 2.0+ KB

In [112]:
# Cambiar a fechas
df_colombia_copy_2['date'] = pd.to_datetime(df_colombia_copy_2['date'])
df_colombia_copy_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   index        39 non-null     int64
 1   date         39 non-null     datetime64[ns]
 2   localName    39 non-null     object
 3   name         39 non-null     object
 4   countryCode  39 non-null     object
 5   fixed        39 non-null     object
dtypes: datetime64[ns](1), int64(1), object(4)
memory usage: 2.0+ KB

### Outliers

Un outlier, o dato atípico, es una observación en un conjunto de datos que se desvía significativamente del comportamiento general del resto. Son valores extremos, "ovejas negras" que rompen el patrón, indicando anomalías, errores de medición o eventos inusuales. Su identificación es crucial para evitar sesgos en promedios y análisis.

In [119]:
# Crear un dataframe
# Crear dataset con 50 registros y outliers intencionales
np.random.seed(42)

# Datos normales
edades_normales = np.random.normal(35, 10, 45)  # 45 datos normales
edades_outliers = np.array([15, 16, 65, 70, 120])  # 5 outliers

salarios_normales = np.random.normal(50000, 15000, 45)
salarios_outliers = np.array([5000, 150000, 200000, 250000, 500000])

df = pd.DataFrame({
    'id': range(1, 51),
    'edad': np.concatenate([edades_normales, edades_outliers]),
    'salario': np.concatenate([salarios_normales, salarios_outliers]),
    'puntuacion': np.random.randint(1, 100, 50),
    'habitaciones': np.random.randint(1, 5, 50)
})

# Añadir un outlier en habitaciones
df.loc[10, 'habitaciones'] = 15

In [122]:
# Rango intercuartilico metodo

def detectar_outliers_iqr(df, columna):
    Q1 = df[columna].quantile(0.25)
    Q3 = df[columna].quantile(0.75)
    IQR = Q3 - Q1
    limite_inferior = Q1 - 1.5 * IQR
    limite_superior = Q3 + 1.5 * IQR
    
    outliers = df[(df[columna] < limite_inferior) | (df[columna] > limite_superior)]
    
    print(f"\n   Columna: {columna}")
    print(f"   Q1 (25%): {Q1:.2f}")
    print(f"   Q3 (75%): {Q3:.2f}")
    print(f"   IQR: {IQR:.2f}")
    print(f"   Límite inferior: {limite_inferior:.2f}")
    print(f"   Límite superior: {limite_superior:.2f}")
    print(f"   Outliers detectados: {len(outliers)}")
    print(f"   Valores outliers: {outliers[columna].tolist()}")
    
    return outliers

In [123]:
# Ejemplo de aplicacion
# Aplicar a todas las columnas numéricas
columnas_numericas = ['edad', 'salario', 'puntuacion', 'habitaciones']
outliers_iqr = {}

for col in columnas_numericas:
    outliers_iqr[col] = detectar_outliers_iqr(df, col)

   Columna: edad
   Q1 (25%): 25.13
   Q3 (75%): 39.66
   IQR: 14.53
   Límite inferior: 3.34
   Límite superior: 61.46
   Outliers detectados: 3
   Valores outliers: [65.0, 70.0, 120.0]

   Columna: salario
   Q1 (25%): 42287.87
   Q3 (75%): 63909.66
   IQR: 21621.79
   Límite inferior: 9855.19
   Límite superior: 96342.34
   Outliers detectados: 5
   Valores outliers: [5000.0, 150000.0, 200000.0, 250000.0, 500000.0]

   Columna: puntuacion
   Q1 (25%): 27.00
   Q3 (75%): 76.50
   IQR: 49.50
   Límite inferior: -47.25
   Límite superior: 150.75
   Outliers detectados: 0
   Valores outliers: []

   Columna: habitaciones
   Q1 (25%): 2.00
   Q3 (75%): 4.00
   IQR: 2.00
   Límite inferior: -1.00
   Límite superior: 7.00
   Outliers detectados: 1
   Valores outliers: [15]

In [127]:
# Metodo z-score

def detectar_outliers_zscore(df, columna, umbral=3):
    media = df[columna].mean()
    std = df[columna].std()
    z_scores = np.abs((df[columna] - media) / std)
    outliers = df[z_scores > umbral]
    
    print(f"\n  Columna: {columna}")
    print(f"   Media: {media:.2f}")
    print(f"   Desviación estándar: {std:.2f}")
    print(f"   Umbral Z-score: {umbral}")
    print(f"   Outliers detectados: {len(outliers)}")
    print(f"   Valores outliers: {outliers[columna].tolist()}")
    
    # Mostrar Z-scores de los outliers
    if len(outliers) > 0:
        print(f"   Z-scores: {z_scores[outliers.index].tolist()}")
    
    return outliers

In [128]:
# Ejemplo de aplicacion
# Aplicar a todas las columnas numéricas
columnas_numericas = ['edad', 'salario', 'puntuacion', 'habitaciones']
outliers_iqr = {}

for col in columnas_numericas:
    outliers_iqr[col] = detectar_outliers_zscore(df, col,umbral = 3)

  Columna: edad
   Media: 35.27
   Desviación estándar: 16.98
   Umbral Z-score: 3
   Outliers detectados: 1
   Valores outliers: [120.0]
   Z-scores: [4.990146352598266]

  Columna: salario
   Media: 67351.45
   Desviación estándar: 74317.63
   Umbral Z-score: 3
   Outliers detectados: 1
   Valores outliers: [500000.0]
   Z-scores: [5.821614250884962]

  Columna: puntuacion
   Media: 50.98
   Desviación estándar: 31.65
   Umbral Z-score: 3
   Outliers detectados: 0
   Valores outliers: []

  Columna: habitaciones
   Media: 3.18
   Desviación estándar: 1.99
   Umbral Z-score: 3
   Outliers detectados: 1
   Valores outliers: [15]
   Z-scores: [5.949900986564601]

## <font color = darkblue> Selección y filtrado

La selección y el filtrado son procesos fundamentales en el análisis de datos que permiten aislar información relevante, mejorar la precisión de los modelos y agilizar la toma de decisiones al eliminar el "ruido" o datos innecesarios. Estas técnicas se aplican para trabajar con subconjuntos de datos más manejables y enfocados.

### Operador de indexación básica []

Se usa principalmente para seleccionar columnas por nombre, pero también puede filtrar filas si se usa un corte (slice).

In [15]:
# Leer el archivo titanic
df = pd.read_csv(
    "titanic.csv",
    header = 0,
    sep = ";"
)

# Obtener el nombre de las columnas
df.columns

Index(['Id_Pasajero', 'Survived', 'Clase', 'Nombre', 'Sexo', 'Edad',
       'Familiares', 'Tiquete', 'Tarifa', 'Cabina', 'Embarcado'],
      dtype='object')

In [21]:
# Obtener la columna Edad
Edades = df['Edad']    # Devuelve una serie

Edades.head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: Edad, dtype: float64

In [19]:
# Obtener las columnas Id_Pasajero, Nombre y Edad
Pasajeros = df[['Id_Pasajero','Nombre','Edad']]     # Devuelve un dataframe

Pasajeros.head()

   Id_Pasajero                                             Nombre  Edad
0            1                            Braund, Mr. Owen Harris  22.0
1            2  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2            3                             Heikkinen, Miss. Laina  26.0
3            4       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4            5                           Allen, Mr. William Henry  35.0

### .iloc

El método .iloc en Pandas se utiliza para seleccionar datos de un DataFrame o Serie basándose exclusivamente en su posición entera (índice numérico de 0 a length-1). Es fundamental para la indexación posicional, permitiendo extraer filas y columnas específicas mediante enteros, listas, cortes (slices) o booleanos, sin depender de los nombres de etiquetas.

In [22]:
# Acceder a la primera fila en Pasajeros
Pasajeros.iloc[0]

Id_Pasajero                          1
Nombre         Braund, Mr. Owen Harris
Edad                              22.0
Name: 0, dtype: object

In [23]:
# Acceder a la ultima fila
Pasajeros.iloc[-1]      # Se utiliza el -1 para acceder al ultimo elemento

Id_Pasajero                    891
Nombre         Dooley, Mr. Patrick
Edad                          32.0
Name: 890, dtype: object

In [24]:
# Acceder a la fila 3
Pasajeros.iloc[2]       # Se usa el dos porque la indexacion comienza en 0

Id_Pasajero                         3
Nombre         Heikkinen, Miss. Laina
Edad                             26.0
Name: 2, dtype: object

In [25]:
# Acceder a la penultima fila
Pasajeros.iloc[-2]

Id_Pasajero                      890
Nombre         Behr, Mr. Karl Howell
Edad                            26.0
Name: 889, dtype: object

In [27]:
# Acceder a la primera columna (Indices)
Pasajeros.iloc[:,0]    # Se usan : para decir que acceda a todos los elementos y otorga una serie

0        1
1        2
2        3
3        4
4        5
      ...
886    887
887    888
888    889
889    890
890    891
Name: Id_Pasajero, Length: 891, dtype: int64

In [30]:
# Acceder a la tercer columna (Edades)
Pasajeros.iloc[:,2]

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Edad, Length: 891, dtype: float64

In [33]:
# Acceder a las primeras 4 filas
Pasajeros.iloc[0:4]

   Id_Pasajero                                             Nombre  Edad
0            1                            Braund, Mr. Owen Harris  22.0
1            2  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2            3                             Heikkinen, Miss. Laina  26.0
3            4       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0

In [34]:
# Lo anterior tambien se puede de la siguiente manera
Pasajeros.iloc[:4]

   Id_Pasajero                                             Nombre  Edad
0            1                            Braund, Mr. Owen Harris  22.0
1            2  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2            3                             Heikkinen, Miss. Laina  26.0
3            4       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0

In [40]:
# Acceder a las filas 2,3,4,5,6
Pasajeros.iloc[1:6]

   Id_Pasajero                                             Nombre  Edad
1            2  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2            3                             Heikkinen, Miss. Laina  26.0
3            4       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4            5                           Allen, Mr. William Henry  35.0
5            6                                   Moran, Mr. James   NaN

In [37]:
# Acceder a la primera y tercera columnas
Pasajeros.iloc[:,[0,2]]

     Id_Pasajero  Edad
0              1  22.0
1              2  38.0
2              3  26.0
3              4  35.0
4              5  35.0
..           ...   ...
886          887  27.0
887          888  19.0
888          889   NaN
889          890  26.0
890          891  32.0

[891 rows x 2 columns]

In [39]:
# Acceder a las filas 5,6,8,10 y a las columnas 1 y 3
Pasajeros.iloc[[4,5,7,10],[0,2]]

    Id_Pasajero  Edad
4             5  35.0
5             6   NaN
7             8   2.0
10           11   4.0

### .loc

El método .loc en Pandas es un indexador basado en etiquetas utilizado para seleccionar, filtrar y manipular filas y columnas en DataFrames y Series. Permite acceder a datos usando nombres de filas/columnas en lugar de posiciones numéricas, incluyendo el límite superior en los cortes (slicing).

In [43]:
# Acceder a la primera fila
Pasajeros.loc[0]

Id_Pasajero                          1
Nombre         Braund, Mr. Owen Harris
Edad                              22.0
Name: 0, dtype: object

In [47]:
# Acceder a todas las filas y a la columna nombre
Pasajeros.loc[:,"Nombre"]

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Nombre, Length: 891, dtype: object

In [49]:
# Acceder a las primeras 5 filas y a la columna nombre
Pasajeros.loc[:4,"Nombre"]

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Nombre, dtype: object

In [50]:
# Acceder a las filas 1,2,6,10 y a la columna edad
Pasajeros.loc[[0,1,5,9],"Edad"]

0    22.0
1    38.0
5     NaN
9    14.0
Name: Edad, dtype: float64

In [51]:
# Acceder a las filas 1,2,6,10 y a las columnas id y edad
Pasajeros.loc[[0,1,5,9],["Id_Pasajero","Edad"]]

   Id_Pasajero  Edad
0            1  22.0
1            2  38.0
5            6   NaN
9           10  14.0

### Filtros booleanos básicos

Los filtros booleanos en pandas permiten seleccionar subconjuntos de datos (filas) basados en condiciones lógicas aplicadas a los valores de las columnas. Se crea una "máscara" booleana (True/False) usando operadores de comparación (>,<,>=,<=,==,!=) o métodos como .isin(), aplicándola luego entre corchetes df[condicion]

In [57]:
# Leer dataset titanic
df = pd.read_csv('titanic.csv', 
                 sep=';',
                header= 0)

# Filtrar pasajeras mujeres (Sexo == 'Femenino')
mujeres = df[df['Sexo'] == 'Femenino']

# Ver la cantidad de mujeres
mujeres.shape

(314, 11)

In [61]:
# Filtrar personas menores que 18 años
menores = df[df['Edad'] <= 18]

# Imprimir las primeras cinco filas
menores.head()

,Id_Pasajero,Survived,Clase,Nombre,Sexo,Edad,Familiares,Tiquete,Tarifa,Cabina,Embarcado
7,8,0,3,"Palsson, Master. Gosta Leonard",Masculino,2.0,1,349909,21.08,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",Femenino,14.0,0,237736,30.07,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",Femenino,4.0,1,PP 9549,16.70,G6,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",Femenino,14.0,0,350406,7.85,NaN,S
16,17,0,3,"Rice, Master. Eugene",Masculino,2.0,1,382652,29.13,NaN,Q

In [63]:
# Filtrar sobrevivientes
sobrevivientes = df[df['Survived'] == 1]

# Imprimir cinco primeros registros
sobrevivientes.head()

,Id_Pasajero,Survived,Clase,Nombre,Sexo,Edad,Familiares,Tiquete,Tarifa,Cabina,Embarcado
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Femenino,38.0,0,PC 17599,71.28,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",Femenino,26.0,0,STON/O2. 3101282,7.93,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Femenino,35.0,0,113803,53.10,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",Femenino,27.0,2,347742,11.13,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",Femenino,14.0,0,237736,30.07,NaN,C

In [64]:
# Otra manera de filtrar sobrevivientes
sobrevivientes = df[df['Survived'] != 0]

# Imprimir cinco primeros registros
sobrevivientes.head()

,Id_Pasajero,Survived,Clase,Nombre,Sexo,Edad,Familiares,Tiquete,Tarifa,Cabina,Embarcado
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Femenino,38.0,0,PC 17599,71.28,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",Femenino,26.0,0,STON/O2. 3101282,7.93,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Femenino,35.0,0,113803,53.10,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",Femenino,27.0,2,347742,11.13,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",Femenino,14.0,0,237736,30.07,NaN,C

In [68]:
# Mujeres que sobrevivieron (AND: &) estos se pueden usar
mujeres_sobrevivientes = df[(df['Sexo'] == 'Femenino') & (df['Survived'] == 1)]

# Imprimir cinco filas
mujeres_sobrevivientes.head()

,Id_Pasajero,Survived,Clase,Nombre,Sexo,Edad,Familiares,Tiquete,Tarifa,Cabina,Embarcado
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Femenino,38.0,0,PC 17599,71.28,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",Femenino,26.0,0,STON/O2. 3101282,7.93,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Femenino,35.0,0,113803,53.10,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",Femenino,27.0,2,347742,11.13,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",Femenino,14.0,0,237736,30.07,NaN,C

In [71]:
# Hombres menores que no sobrevivieron
hombres_menores_no_sobrevivieron = df[(df['Sexo'] == 'Masculino') & (df['Survived'] == 0) & (df["Edad"] <= 18)]

# Imprimir cinco primeras filas
hombres_menores_no_sobrevivieron.head()

,Id_Pasajero,Survived,Clase,Nombre,Sexo,Edad,Familiares,Tiquete,Tarifa,Cabina,Embarcado
7,8,0,3,"Palsson, Master. Gosta Leonard",Masculino,2.0,1,349909,21.08,NaN,S
16,17,0,3,"Rice, Master. Eugene",Masculino,2.0,1,382652,29.13,NaN,Q
50,51,0,3,"Panula, Master. Juha Niilo",Masculino,7.0,1,3101295,39.69,NaN,S
59,60,0,3,"Goodwin, Master. William Frederick",Masculino,11.0,2,CA 2144,46.90,NaN,S
63,64,0,3,"Skoog, Master. Harald",Masculino,4.0,2,347088,27.90,NaN,S

In [73]:
# Pasajeros de segunda clase o tercera clase (OR: |)
segunda_o_tercera = df[(df['Clase'] == 2) | (df['Clase'] == 3)]

# Imprimir cinco filas
segunda_o_tercera.head()

,Id_Pasajero,Survived,Clase,Nombre,Sexo,Edad,Familiares,Tiquete,Tarifa,Cabina,Embarcado
0,1,0,3,"Braund, Mr. Owen Harris",Masculino,22.0,0,A/5 21171,7.25,NaN,S
2,3,1,3,"Heikkinen, Miss. Laina",Femenino,26.0,0,STON/O2. 3101282,7.93,NaN,S
4,5,0,3,"Allen, Mr. William Henry",Masculino,35.0,0,373450,8.05,NaN,S
5,6,0,3,"Moran, Mr. James",Masculino,NaN,0,330877,8.46,NaN,Q
7,8,0,3,"Palsson, Master. Gosta Leonard",Masculino,2.0,1,349909,21.08,NaN,S

In [74]:
# Pasajeros sin edad registrada (Edad es nulo)
sin_edad = df[df['Edad'].isna()]

# Imprimir cinco primeras filas
sin_edad.head()

,Id_Pasajero,Survived,Clase,Nombre,Sexo,Edad,Familiares,Tiquete,Tarifa,Cabina,Embarcado
5,6,0,3,"Moran, Mr. James",Masculino,NaN,0,330877,8.46,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",Masculino,NaN,0,244373,13.00,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",Femenino,NaN,0,2649,7.23,NaN,C
26,27,0,3,"Emir, Mr. Farred Chehab",Masculino,NaN,0,2631,7.23,NaN,C
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",Femenino,NaN,0,330959,7.88,NaN,Q

In [77]:
# Pasajeros sin edad registrada (Edad es nulo) y femeninas
sin_edad_mujeres = df[(df['Edad'].isna()) & (df['Sexo'] == 'Femenino')]

# Imprimir cinco primeras filas
sin_edad_mujeres.head()

,Id_Pasajero,Survived,Clase,Nombre,Sexo,Edad,Familiares,Tiquete,Tarifa,Cabina,Embarcado
19,20,1,3,"Masselmani, Mrs. Fatima",Femenino,NaN,0,2649,7.23,NaN,C
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",Femenino,NaN,0,330959,7.88,NaN,Q
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",Femenino,NaN,0,PC 17569,146.52,B78,C
32,33,1,3,"Glynn, Miss. Mary Agatha",Femenino,NaN,0,335677,7.75,NaN,Q
47,48,1,3,"O'Driscoll, Miss. Bridget",Femenino,NaN,0,14311,7.75,NaN,Q

In [78]:
# Pasajeros con edad registrada (NO nulo)
con_edad = df[df['Edad'].notna()]

# Imprimir cinco registros
con_edad.head()

,Id_Pasajero,Survived,Clase,Nombre,Sexo,Edad,Familiares,Tiquete,Tarifa,Cabina,Embarcado
0,1,0,3,"Braund, Mr. Owen Harris",Masculino,22.0,0,A/5 21171,7.25,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Femenino,38.0,0,PC 17599,71.28,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",Femenino,26.0,0,STON/O2. 3101282,7.93,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Femenino,35.0,0,113803,53.10,C123,S
4,5,0,3,"Allen, Mr. William Henry",Masculino,35.0,0,373450,8.05,NaN,S

In [79]:
# Niños menores de 12 años (con edad no nula)
menores_12 = df[(df['Edad'].notna()) & (df['Edad'] < 12)]

# Imprimir cinco filas
menores_12.head()

,Id_Pasajero,Survived,Clase,Nombre,Sexo,Edad,Familiares,Tiquete,Tarifa,Cabina,Embarcado
7,8,0,3,"Palsson, Master. Gosta Leonard",Masculino,2.0,1,349909,21.08,NaN,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",Femenino,4.0,1,PP 9549,16.70,G6,S
16,17,0,3,"Rice, Master. Eugene",Masculino,2.0,1,382652,29.13,NaN,Q
24,25,0,3,"Palsson, Miss. Torborg Danira",Femenino,8.0,1,349909,21.08,NaN,S
43,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",Femenino,3.0,2,SC/Paris 2123,41.58,NaN,C

## <font color = darkblue> Exploración y limpieza

head, tail, info, describe, dtypes

Valores nulos (isnull, dropna, fillna, interpolate)

Duplicados (duplicated, drop_duplicates)

Renombrar columnas y cambio de tipos

Outliers y filtros condicionales

## <font color = darkblue> Selección y filtrado

[] (por etiquetas)

.loc (por nombre)

.iloc (por posición)

Filtros booleanos

query() (estilo SQL)

where y mask

## <font color = darkblue> Transformación y manipulación

Crear/eliminar columnas (assign, drop)

map, apply, applymap

replace, str (métodos string vectorizados)

dt (fechas), cat (categóricas)

## <font color = darkblue> Agrupación y agregación

groupby básico y múltiples columnas

agg con diccionarios y funciones personalizadas

transform y filter dentro de grupos

pivot_table (tablas dinámicas)

crosstab

rolling, expanding (ventanas temporales)

## <font color = darkblue> Combinación de datos

concat (apilar filas o columnas)

merge (JOINs: inner, outer, left, right, cross)

join (por índice)

compare (diferencias entre DataFrames)

## Reshaping

melt (ancho a largo)

pivot (largo a ancho)

stack / unstack

explode (listas a filas)

## Series de tiempo

to_datetime, date_range

Resample (upsampling/downsampling)

shift, diff, pct_change

Ventanas móviles

Timezone handling

## Performance y optimización

Uso de eval y query

numba con apply

categorical para reducir memoria

Uso de chunksize en lectura

pandas vs dask (introducción)

Escritura eficiente (Parquet vs CSV)

## Escritura de archivos

to_csv, to_excel, to_json, to_parquet, to_feather

to_sql, to_pickle, to_markdown, to_clipboard

Exportar a HTML, LaTeX, string

### Cambiar el nombre de las columnas

In [13]:
dataset = dataset.rename(columns= {'4046':'PLU 4046 venta',
                                   '4225':'PLU 4225 venta',
                                   '4770':'PLU 4770 venta',
                                   'Total Volume':'Aguacates_vendidos',
                                   'AveragePrice':'Precio_promedio',
                                   'Total Bags':'Bolsas_Totales',
                                   'Small Bags':'Bolsas_chicas',
                                   'Large Bags':'Bolsas_grandes',
                                   'XLarge Bags':'Bolsas_extragrandes',
                                   'type':'tipo',
                                   'Date':'Fecha'})
dataset.columns.values

array(['Fecha', 'Precio_promedio', 'Aguacates_vendidos', 'PLU 4046 venta',
       'PLU 4225 venta', 'PLU 4770 venta', 'Bolsas_Totales',
       'Bolsas_chicas', 'Bolsas_grandes', 'Bolsas_extragrandes', 'tipo',
       'year', 'region'], dtype=object)

### Seleccionar columnas

In [14]:
dataset["Fecha"]   # Seleccionar la columna nombre

0    2015-12-27
1    2015-12-20
2    2015-12-13
3    2015-12-06
4    2015-11-29
        ...
7    2018-02-04
8    2018-01-28
9    2018-01-21
10   2018-01-14
11   2018-01-07
Name: Fecha, Length: 18249, dtype: datetime64[ns]

In [15]:
dataset[["tipo", 'Bolsas_Totales']]   # Seleccionar dos columnas

            tipo  Bolsas_Totales
0   conventional         8696.87
1   conventional         9505.56
2   conventional         8145.35
3   conventional         5811.16
4   conventional         6183.95
..           ...             ...
7        organic        13498.67
8        organic         9264.84
9        organic         9394.11
10       organic        10969.54
11       organic        12014.15

[18249 rows x 2 columns]

#### Mostrar los primeros cinco elementos del dataframe

In [16]:
dataset.head(5)

,Fecha,Precio_promedio,Aguacates_vendidos,PLU 4046 venta,PLU 4225 venta,PLU 4770 venta,Bolsas_Totales,Bolsas_chicas,Bolsas_grandes,Bolsas_extragrandes,tipo,year,region
0,2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany
1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany
2,2015-12-13,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.0,conventional,2015,Albany
3,2015-12-06,1.08,78992.15,1132.00,71976.41,72.58,5811.16,5677.40,133.76,0.0,conventional,2015,Albany
4,2015-11-29,1.28,51039.60,941.48,43838.39,75.78,6183.95,5986.26,197.69,0.0,conventional,2015,Albany

#### Mostrar los últimos cinco elementos del dataset

In [17]:
dataset.tail(5)

,Fecha,Precio_promedio,Aguacates_vendidos,PLU 4046 venta,PLU 4225 venta,PLU 4770 venta,Bolsas_Totales,Bolsas_chicas,Bolsas_grandes,Bolsas_extragrandes,tipo,year,region
7,2018-02-04,1.63,17074.83,2046.96,1529.20,0.00,13498.67,13066.82,431.85,0.0,organic,2018,WestTexNewMexico
8,2018-01-28,1.71,13888.04,1191.70,3431.50,0.00,9264.84,8940.04,324.80,0.0,organic,2018,WestTexNewMexico
9,2018-01-21,1.87,13766.76,1191.92,2452.79,727.94,9394.11,9351.80,42.31,0.0,organic,2018,WestTexNewMexico
10,2018-01-14,1.93,16205.22,1527.63,2981.04,727.01,10969.54,10919.54,50.00,0.0,organic,2018,WestTexNewMexico
11,2018-01-07,1.62,17489.58,2894.77,2356.13,224.53,12014.15,11988.14,26.01,0.0,organic,2018,WestTexNewMexico

### Nombres de las columnas

In [18]:
dataset.columns

Index(['Fecha', 'Precio_promedio', 'Aguacates_vendidos', 'PLU 4046 venta',
       'PLU 4225 venta', 'PLU 4770 venta', 'Bolsas_Totales', 'Bolsas_chicas',
       'Bolsas_grandes', 'Bolsas_extragrandes', 'tipo', 'year', 'region'],
      dtype='object')

#### Mostrar un resumen del dataframe

In [19]:
dataset.describe().T

,count,mean,min,25%,50%,75%,max,std
Fecha,18249,2016-08-13 23:30:43.498273792,2015-01-04 00:00:00,2015-10-25 00:00:00,2016-08-14 00:00:00,2017-06-04 00:00:00,2018-03-25 00:00:00,NaN
Precio_promedio,18249.0,1.405978,0.44,1.1,1.37,1.66,3.25,0.402677
Aguacates_vendidos,18249.0,850644.013009,84.56,10838.58,107376.76,432962.29,62505646.52,3453545.355399
PLU 4046 venta,18249.0,293008.424531,0.0,854.07,8645.3,111020.2,22743616.17,1264989.081763
PLU 4225 venta,18249.0,295154.568356,0.0,3008.78,29061.02,150206.86,20470572.61,1204120.401135
PLU 4770 venta,18249.0,22839.735993,0.0,0.0,184.99,6243.42,2546439.11,107464.068435
Bolsas_Totales,18249.0,239639.20206,0.0,5088.64,39743.83,110783.37,19373134.37,986242.399216
Bolsas_chicas,18249.0,182194.686696,0.0,2849.42,26362.82,83337.67,13384586.8,746178.514962
Bolsas_grandes,18249.0,54338.088145,0.0,127.47,2647.71,22029.25,5719096.61,243965.964547
Bolsas_extragrandes,18249.0,3106.426507,0.0,0.0,0.0,132.5,551693.65,17692.894652
year,18249.0,2016.147899,2015.0,2015.0,2016.0,2017.0,2018.0,0.939938

#### Mostrar un resumen del dataframe

In [20]:
dataset.dtypes

Fecha                  datetime64[ns]
Precio_promedio               float64
Aguacates_vendidos            float64
PLU 4046 venta                float64
PLU 4225 venta                float64
PLU 4770 venta                float64
Bolsas_Totales                float64
Bolsas_chicas                 float64
Bolsas_grandes                float64
Bolsas_extragrandes           float64
tipo                           object
year                            int64
region                         object
dtype: object

### Seleccionando lineas - [ i : j ] 

**Observación:**</font> La indexación tiene origen en cero y en las particiones(*slices*) la línea con índice i es **incluída** y la línea con índice j **no es incluída** en el resultado.

In [21]:
dataset[:4]     # Primeras cuatro filas

,Fecha,Precio_promedio,Aguacates_vendidos,PLU 4046 venta,PLU 4225 venta,PLU 4770 venta,Bolsas_Totales,Bolsas_chicas,Bolsas_grandes,Bolsas_extragrandes,tipo,year,region
0,2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany
1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany
2,2015-12-13,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.0,conventional,2015,Albany
3,2015-12-06,1.08,78992.15,1132.00,71976.41,72.58,5811.16,5677.40,133.76,0.0,conventional,2015,Albany

### Utilizando .loc para selecciones

**Observación:**</font> Selecciona un grupo de líneas y columnas según las etiquetas o una matriz booleana.

In [22]:
# Metodo .loc
dataset.loc[0]   # Obtenes los indices 2

,Fecha,Precio_promedio,Aguacates_vendidos,PLU 4046 venta,PLU 4225 venta,PLU 4770 venta,Bolsas_Totales,Bolsas_chicas,Bolsas_grandes,Bolsas_extragrandes,tipo,year,region
0,2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.00,conventional,2015,Albany
0,2015-12-27,0.99,386100.49,292097.36,27350.92,297.90,66354.31,48605.95,17748.36,0.00,conventional,2015,Atlanta
0,2015-12-27,1.17,596819.40,40450.49,394104.02,17353.79,144911.10,142543.88,2367.22,0.00,conventional,2015,BaltimoreWashington
0,2015-12-27,0.97,62909.69,30482.25,2971.94,5894.40,23561.10,23520.19,5.69,35.22,conventional,2015,Boise
0,2015-12-27,1.13,450816.39,3886.27,346964.70,13952.56,86012.86,85913.60,99.26,0.00,conventional,2015,Boston
...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,2018-03-25,1.04,14503.47,78.95,148.37,0.00,14276.15,9992.31,4283.84,0.00,organic,2018,Syracuse
0,2018-03-25,1.41,10028.49,138.15,773.22,0.00,9117.12,8208.82,908.30,0.00,organic,2018,Tampa
0,2018-03-25,1.55,1559967.20,121007.94,342853.10,1070.24,1093861.09,902774.79,190941.84,144.46,organic,2018,TotalUS
0,2018-03-25,1.60,271723.08,26996.28,77861.39,117.56,166747.85,87108.00,79495.39,144.46,organic,2018,West
0,2018-03-25,1.62,15303.40,2325.30,2171.66,0.00,10806.44,10569.80,236.64,0.00,organic,2018,WestTexNewMexico

In [23]:
# Leer dos Nombres completos (filas)
dataset.loc[[2, 3]]   # Indices 2 y 3 mostrar

,Fecha,Precio_promedio,Aguacates_vendidos,PLU 4046 venta,PLU 4225 venta,PLU 4770 venta,Bolsas_Totales,Bolsas_chicas,Bolsas_grandes,Bolsas_extragrandes,tipo,year,region
2,2015-12-13,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.00,conventional,2015,Albany
2,2015-12-13,0.96,417772.47,324932.28,31019.08,275.80,61545.31,38903.57,22628.21,13.53,conventional,2015,Atlanta
2,2015-12-13,1.15,619509.33,44400.26,399851.59,24291.20,150966.28,149070.40,1895.88,0.00,conventional,2015,BaltimoreWashington
2,2015-12-13,0.99,58461.05,27148.61,2985.73,6458.44,21868.27,21842.87,4.44,20.96,conventional,2015,Boise
2,2015-12-13,1.01,549945.76,4641.02,455362.38,219.40,89722.96,89523.38,199.58,0.00,conventional,2015,Boston
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3,2018-03-04,1.42,3061.66,395.14,89.31,0.00,2577.21,721.50,1855.71,0.00,organic,2018,Syracuse
3,2018-03-04,1.51,9851.33,223.68,839.86,0.00,8787.79,7327.76,1460.03,0.00,organic,2018,Tampa
3,2018-03-04,1.52,1634430.77,142345.03,390129.50,1225.97,1099871.68,831885.50,267818.31,167.87,organic,2018,TotalUS
3,2018-03-04,1.46,347373.17,25990.60,71213.19,79.01,250090.37,85835.17,164087.33,167.87,organic,2018,West
3,2018-03-04,1.54,17393.30,1832.24,1905.57,0.00,13655.49,13401.93,253.56,0.00,organic,2018,WestTexNewMexico

In [24]:
# Mostrar dos nombres y solo las columnas Motor y Valor
dataset.loc[[2, 4], ['tipo', 'Aguacates_vendidos']]

            tipo  Aguacates_vendidos
2   conventional           118220.22
2   conventional           417772.47
2   conventional           619509.33
2   conventional            58461.05
2   conventional           549945.76
..           ...                 ...
4        organic             4162.96
4        organic             9144.20
4        organic          1459852.55
4        organic           301985.61
4        organic            18421.24

[864 rows x 2 columns]

In [25]:
# Mostrar todas las filas, pero las columnas motor y valor
dataset.loc[:, ['tipo', 'Aguacates_vendidos']]

            tipo  Aguacates_vendidos
0   conventional            64236.62
1   conventional            54876.98
2   conventional           118220.22
3   conventional            78992.15
4   conventional            51039.60
..           ...                 ...
7        organic            17074.83
8        organic            13888.04
9        organic            13766.76
10       organic            16205.22
11       organic            17489.58

[18249 rows x 2 columns]

### Utilizando .iloc para selecciones

**Observación:**</font> Selecciona con base en los índices, es decir, utiliza la posición de las informaciones.

In [26]:
dataset.iloc[[1]]     # Obtener la fila 1 (Segunda fila)

,Fecha,Precio_promedio,Aguacates_vendidos,PLU 4046 venta,PLU 4225 venta,PLU 4770 venta,Bolsas_Totales,Bolsas_chicas,Bolsas_grandes,Bolsas_extragrandes,tipo,year,region
1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany

In [27]:
dataset.iloc[1:4]     # Obtener las filas 1,2,3, y 4

,Fecha,Precio_promedio,Aguacates_vendidos,PLU 4046 venta,PLU 4225 venta,PLU 4770 venta,Bolsas_Totales,Bolsas_chicas,Bolsas_grandes,Bolsas_extragrandes,tipo,year,region
1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany
2,2015-12-13,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.0,conventional,2015,Albany
3,2015-12-06,1.08,78992.15,1132.00,71976.41,72.58,5811.16,5677.40,133.76,0.0,conventional,2015,Albany

In [28]:
dataset.iloc[0:4,[0,5,2]]  # Obtener las primeras 5 filas y las columnas 0, 5, y 2

       Fecha  PLU 4770 venta  Aguacates_vendidos
0 2015-12-27           48.16            64236.62
1 2015-12-20           58.33            54876.98
2 2015-12-13          130.50           118220.22
3 2015-12-06           72.58            78992.15

In [29]:
dataset.iloc[[1,52,10],[0,5,2]] # Obtener las filas 1,52,10 y las columnas 0, 5 y 2

        Fecha  PLU 4770 venta  Aguacates_vendidos
1  2015-12-20           58.33            54876.98
0  2015-12-27          297.90           386100.49
10 2015-10-18          117.07            84843.44

In [30]:
dataset.iloc[:,[1,5,2]]   # Obtener las columnas 0,5,2

    Precio_promedio  PLU 4770 venta  Aguacates_vendidos
0              1.33           48.16            64236.62
1              1.35           58.33            54876.98
2              0.93          130.50           118220.22
3              1.08           72.58            78992.15
4              1.28           75.78            51039.60
..              ...             ...                 ...
7              1.63            0.00            17074.83
8              1.71            0.00            13888.04
9              1.87          727.94            13766.76
10             1.93          727.01            16205.22
11             1.62          224.53            17489.58

[18249 rows x 3 columns]

## <font color = darkblue> Filtrado y consultas

Una de las operaciones más habituales es filtrar, poder seleccionar un subconjunto de los datos en base a los valores de uno o varias columnas.

In [31]:
# Filtrar precios mayores que 1 
mayores_1 = dataset[dataset["Precio_promedio"] > 1]
mayores_1

,Fecha,Precio_promedio,Aguacates_vendidos,PLU 4046 venta,PLU 4225 venta,PLU 4770 venta,Bolsas_Totales,Bolsas_chicas,Bolsas_grandes,Bolsas_extragrandes,tipo,year,region
0,2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany
1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany
3,2015-12-06,1.08,78992.15,1132.00,71976.41,72.58,5811.16,5677.40,133.76,0.0,conventional,2015,Albany
4,2015-11-29,1.28,51039.60,941.48,43838.39,75.78,6183.95,5986.26,197.69,0.0,conventional,2015,Albany
5,2015-11-22,1.26,55979.78,1184.27,48067.99,43.61,6683.91,6556.47,127.44,0.0,conventional,2015,Albany
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7,2018-02-04,1.63,17074.83,2046.96,1529.20,0.00,13498.67,13066.82,431.85,0.0,organic,2018,WestTexNewMexico
8,2018-01-28,1.71,13888.04,1191.70,3431.50,0.00,9264.84,8940.04,324.80,0.0,organic,2018,WestTexNewMexico
9,2018-01-21,1.87,13766.76,1191.92,2452.79,727.94,9394.11,9351.80,42.31,0.0,organic,2018,WestTexNewMexico
10,2018-01-14,1.93,16205.22,1527.63,2981.04,727.01,10969.54,10919.54,50.00,0.0,organic,2018,WestTexNewMexico
11,2018-01-07,1.62,17489.58,2894.77,2356.13,224.53,12014.15,11988.14,26.01,0.0,organic,2018,WestTexNewMexico

In [32]:
# Filtrar origin usa
Convencionales = dataset[dataset["tipo"] == "conventional"]
Convencionales.describe().T

,count,mean,min,25%,50%,75%,max,std
Fecha,9126,2016-08-14 00:00:00.000000256,2015-01-04 00:00:00,2015-10-25 00:00:00,2016-08-14 00:00:00,2017-06-04 00:00:00,2018-03-25 00:00:00,NaN
Precio_promedio,9126.0,1.15804,0.46,0.98,1.13,1.32,2.22,0.263041
Aguacates_vendidos,9126.0,1653212.898456,33699.68,198908.61,408325.53,1030992.0475,62505646.52,4747891.870241
PLU 4046 venta,9126.0,578611.649925,72.06,31935.38,104706.745,364716.87,22743616.17,1742500.724643
PLU 4225 venta,9126.0,574805.318859,1518.0,50918.85,136114.74,415169.6425,20470572.61,1655581.97074
PLU 4770 venta,9126.0,45405.796798,0.0,556.88,6035.945,21181.83,2546439.11,148575.027836
Bolsas_Totales,9126.0,454390.130901,3047.17,57247.935,98896.755,291695.9025,19373134.37,1358740.70178
Bolsas_chicas,9126.0,346721.795885,1119.18,43296.3225,75727.26,204396.585,13384586.8,1027419.892979
Bolsas_grandes,9126.0,101457.698855,0.0,2308.1075,14582.63,59910.8325,5719096.61,337454.516031
Bolsas_extragrandes,9126.0,6210.635065,0.0,0.0,122.255,2409.215,551693.65,24631.904345
year,9126.0,2016.147929,2015.0,2015.0,2016.0,2017.0,2018.0,0.939968

In [33]:

dataset.iloc[0,1] = 30

In [34]:
dataset

,Fecha,Precio_promedio,Aguacates_vendidos,PLU 4046 venta,PLU 4225 venta,PLU 4770 venta,Bolsas_Totales,Bolsas_chicas,Bolsas_grandes,Bolsas_extragrandes,tipo,year,region
0,2015-12-27,30.00,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany
1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany
2,2015-12-13,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.0,conventional,2015,Albany
3,2015-12-06,1.08,78992.15,1132.00,71976.41,72.58,5811.16,5677.40,133.76,0.0,conventional,2015,Albany
4,2015-11-29,1.28,51039.60,941.48,43838.39,75.78,6183.95,5986.26,197.69,0.0,conventional,2015,Albany
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7,2018-02-04,1.63,17074.83,2046.96,1529.20,0.00,13498.67,13066.82,431.85,0.0,organic,2018,WestTexNewMexico
8,2018-01-28,1.71,13888.04,1191.70,3431.50,0.00,9264.84,8940.04,324.80,0.0,organic,2018,WestTexNewMexico
9,2018-01-21,1.87,13766.76,1191.92,2452.79,727.94,9394.11,9351.80,42.31,0.0,organic,2018,WestTexNewMexico
10,2018-01-14,1.93,16205.22,1527.63,2981.04,727.01,10969.54,10919.54,50.00,0.0,organic,2018,WestTexNewMexico
11,2018-01-07,1.62,17489.58,2894.77,2356.13,224.53,12014.15,11988.14,26.01,0.0,organic,2018,WestTexNewMexico

In [35]:
dataset[(dataset.Precio_promedio >= 1) & (dataset.tipo == "conventional")]

,Fecha,Precio_promedio,Aguacates_vendidos,PLU 4046 venta,PLU 4225 venta,PLU 4770 venta,Bolsas_Totales,Bolsas_chicas,Bolsas_grandes,Bolsas_extragrandes,tipo,year,region
0,2015-12-27,30.00,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.00,conventional,2015,Albany
1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.00,conventional,2015,Albany
3,2015-12-06,1.08,78992.15,1132.00,71976.41,72.58,5811.16,5677.40,133.76,0.00,conventional,2015,Albany
4,2015-11-29,1.28,51039.60,941.48,43838.39,75.78,6183.95,5986.26,197.69,0.00,conventional,2015,Albany
5,2015-11-22,1.26,55979.78,1184.27,48067.99,43.61,6683.91,6556.47,127.44,0.00,conventional,2015,Albany
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2,2018-03-11,1.00,6906412.50,2442241.76,1695925.97,130983.00,2637261.77,1435608.59,1184730.56,16922.62,conventional,2018,West
8,2018-01-28,1.01,7007265.31,2718390.81,1664995.75,93165.88,2530712.87,1254504.07,1260049.46,16159.34,conventional,2018,West
9,2018-01-21,1.04,7053820.12,2218365.17,1811849.78,106001.28,2917603.89,1196963.03,1707643.76,12997.10,conventional,2018,West
10,2018-01-14,1.05,7577456.14,2249412.86,2028819.77,113257.03,3185966.48,1152416.21,2017353.32,16196.95,conventional,2018,West
11,2018-01-07,1.08,6358768.95,2061960.91,1706532.52,108441.55,2481833.97,1175889.89,1291212.75,14731.33,conventional,2018,West

In [36]:
# Metodo query
dataset.query('Precio_promedio >= 1 and tipo == "conventional"')

,Fecha,Precio_promedio,Aguacates_vendidos,PLU 4046 venta,PLU 4225 venta,PLU 4770 venta,Bolsas_Totales,Bolsas_chicas,Bolsas_grandes,Bolsas_extragrandes,tipo,year,region
0,2015-12-27,30.00,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.00,conventional,2015,Albany
1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.00,conventional,2015,Albany
3,2015-12-06,1.08,78992.15,1132.00,71976.41,72.58,5811.16,5677.40,133.76,0.00,conventional,2015,Albany
4,2015-11-29,1.28,51039.60,941.48,43838.39,75.78,6183.95,5986.26,197.69,0.00,conventional,2015,Albany
5,2015-11-22,1.26,55979.78,1184.27,48067.99,43.61,6683.91,6556.47,127.44,0.00,conventional,2015,Albany
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2,2018-03-11,1.00,6906412.50,2442241.76,1695925.97,130983.00,2637261.77,1435608.59,1184730.56,16922.62,conventional,2018,West
8,2018-01-28,1.01,7007265.31,2718390.81,1664995.75,93165.88,2530712.87,1254504.07,1260049.46,16159.34,conventional,2018,West
9,2018-01-21,1.04,7053820.12,2218365.17,1811849.78,106001.28,2917603.89,1196963.03,1707643.76,12997.10,conventional,2018,West
10,2018-01-14,1.05,7577456.14,2249412.86,2028819.77,113257.03,3185966.48,1152416.21,2017353.32,16196.95,conventional,2018,West
11,2018-01-07,1.08,6358768.95,2061960.91,1706532.52,108441.55,2481833.97,1175889.89,1291212.75,14731.33,conventional,2018,West

In [37]:
dataset.tipo.unique()  # Tipos de aguacates

array(['conventional', 'organic'], dtype=object)

In [38]:
dataset.columns.values

array(['Fecha', 'Precio_promedio', 'Aguacates_vendidos', 'PLU 4046 venta',
       'PLU 4225 venta', 'PLU 4770 venta', 'Bolsas_Totales',
       'Bolsas_chicas', 'Bolsas_grandes', 'Bolsas_extragrandes', 'tipo',
       'year', 'region'], dtype=object)

### Iterar dataframes

In [39]:
for item in dataset:
    print(item)

Fecha
Precio_promedio
Aguacates_vendidos
PLU 4046 venta
PLU 4225 venta
PLU 4770 venta
Bolsas_Totales
Bolsas_chicas
Bolsas_grandes
Bolsas_extragrandes
tipo
year
region

In [40]:
# Agregar una columna e iterar

for index, row in dataset.iterrows():
    dataset.loc[index, "Ingresos"] = row['Precio_promedio']*row['Bolsas_Totales']

dataset.Ingresos

0     17506.4328
1     19252.7088
2     26149.6092
3     21029.4546
4     21923.9981
         ...
7     22002.8321
8     15842.8764
9     17566.9857
10    21171.2122
11    19462.9230
Name: Ingresos, Length: 18249, dtype: float64

## <font color = darkblue> Limpieza de datos

La limpieza de datos es un proceso esencial para preparar los datos sin procesar para las aplicaciones de machine learning (ML) y de inteligencia empresarial (BI). Es posible que los datos sin procesar contengan numerosos errores, que pueden afectar a la precisión de los modelos de ML y dar lugar a predicciones incorrectas y a un impacto empresarial negativo.

### Identificación y tratamiento de valores faltantes (missing values)

Los valores faltantes son datos que no se han almacenado para una variable en una observación. Para identificar y tratarlos, se pueden utilizar métodos de eliminación, imputación o interpolación.

En la libraría Pandas de Python, los valores perdidos se representan con None y NaN (acrónimo de **Not a Number**). Este último es un valor especial de punto flotante reconocido por todos los sistemas que utilizan la representación estándar de punto flotante IEEE. Además, Pandas asigna automáticamente NaN si el valor de una celda es un string vacío '', NA o NaN.

### Identificamos si existen valores faltantes

In [41]:
dataset.isnull()

,Fecha,Precio_promedio,Aguacates_vendidos,PLU 4046 venta,PLU 4225 venta,PLU 4770 venta,Bolsas_Totales,Bolsas_chicas,Bolsas_grandes,Bolsas_extragrandes,tipo,year,region,Ingresos
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [42]:
dataset.iloc[2,2] = None  # Agregamos un dato faltante sin numpy

In [43]:
import numpy as np
dataset.iloc[3,2] = np.nan   # Agregamos un dato faltante con numpy

### ¿Cuántos datos faltantes hay por característica o columna?

In [44]:
dataset.head()

,Fecha,Precio_promedio,Aguacates_vendidos,PLU 4046 venta,PLU 4225 venta,PLU 4770 venta,Bolsas_Totales,Bolsas_chicas,Bolsas_grandes,Bolsas_extragrandes,tipo,year,region,Ingresos
0,2015-12-27,30.00,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany,17506.4328
1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany,19252.7088
2,2015-12-13,0.93,NaN,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.0,conventional,2015,Albany,26149.6092
3,2015-12-06,1.08,NaN,1132.00,71976.41,72.58,5811.16,5677.40,133.76,0.0,conventional,2015,Albany,21029.4546
4,2015-11-29,1.28,51039.60,941.48,43838.39,75.78,6183.95,5986.26,197.69,0.0,conventional,2015,Albany,21923.9981

In [45]:
dataset.isnull().sum()

Fecha                  0
Precio_promedio        0
Aguacates_vendidos     2
PLU 4046 venta         0
PLU 4225 venta         0
PLU 4770 venta         0
Bolsas_Totales         0
Bolsas_chicas          0
Bolsas_grandes         0
Bolsas_extragrandes    0
tipo                   0
year                   0
region                 0
Ingresos               0
dtype: int64

### Datos faltantes por columna

In [46]:
dataset.Aguacates_vendidos.isnull()

0     False
1     False
2      True
3      True
4     False
      ...
7     False
8     False
9     False
10    False
11    False
Name: Aguacates_vendidos, Length: 18249, dtype: bool

## Vamos a ver los registros que tienen datos vacios

In [47]:
dataset[dataset["Aguacates_vendidos"].isnull()== True]

,Fecha,Precio_promedio,Aguacates_vendidos,PLU 4046 venta,PLU 4225 venta,PLU 4770 venta,Bolsas_Totales,Bolsas_chicas,Bolsas_grandes,Bolsas_extragrandes,tipo,year,region,Ingresos
2,2015-12-13,0.93,NaN,794.7,109149.67,130.50,8145.35,8042.21,103.14,0.0,conventional,2015,Albany,26149.6092
3,2015-12-06,1.08,NaN,1132.0,71976.41,72.58,5811.16,5677.40,133.76,0.0,conventional,2015,Albany,21029.4546

### Eliminación de los registros con datos faltantes

In [48]:
dataset = dataset.dropna()
dataset

,Fecha,Precio_promedio,Aguacates_vendidos,PLU 4046 venta,PLU 4225 venta,PLU 4770 venta,Bolsas_Totales,Bolsas_chicas,Bolsas_grandes,Bolsas_extragrandes,tipo,year,region,Ingresos
0,2015-12-27,30.00,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany,17506.4328
1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany,19252.7088
4,2015-11-29,1.28,51039.60,941.48,43838.39,75.78,6183.95,5986.26,197.69,0.0,conventional,2015,Albany,21923.9981
5,2015-11-22,1.26,55979.78,1184.27,48067.99,43.61,6683.91,6556.47,127.44,0.0,conventional,2015,Albany,21491.6676
6,2015-11-15,0.99,83453.76,1368.92,73672.72,93.26,8318.86,8196.81,122.05,0.0,conventional,2015,Albany,19928.9049
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7,2018-02-04,1.63,17074.83,2046.96,1529.20,0.00,13498.67,13066.82,431.85,0.0,organic,2018,WestTexNewMexico,22002.8321
8,2018-01-28,1.71,13888.04,1191.70,3431.50,0.00,9264.84,8940.04,324.80,0.0,organic,2018,WestTexNewMexico,15842.8764
9,2018-01-21,1.87,13766.76,1191.92,2452.79,727.94,9394.11,9351.80,42.31,0.0,organic,2018,WestTexNewMexico,17566.9857
10,2018-01-14,1.93,16205.22,1527.63,2981.04,727.01,10969.54,10919.54,50.00,0.0,organic,2018,WestTexNewMexico,21171.2122
11,2018-01-07,1.62,17489.58,2894.77,2356.13,224.53,12014.15,11988.14,26.01,0.0,organic,2018,WestTexNewMexico,19462.9230

### Eliminar los registros que tienen NA en una columna

In [49]:
dataset.dropna(subset = ['Precio_promedio'], inplace = True)

C:\Users\jorge\AppData\Local\Temp\ipykernel_1708\1088744067.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset.dropna(subset = ['Precio_promedio'], inplace = True)

### Reemplazar los datos nulos por ceros

In [50]:
dataset.fillna(0)

,Fecha,Precio_promedio,Aguacates_vendidos,PLU 4046 venta,PLU 4225 venta,PLU 4770 venta,Bolsas_Totales,Bolsas_chicas,Bolsas_grandes,Bolsas_extragrandes,tipo,year,region,Ingresos
0,2015-12-27,30.00,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany,17506.4328
1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany,19252.7088
4,2015-11-29,1.28,51039.60,941.48,43838.39,75.78,6183.95,5986.26,197.69,0.0,conventional,2015,Albany,21923.9981
5,2015-11-22,1.26,55979.78,1184.27,48067.99,43.61,6683.91,6556.47,127.44,0.0,conventional,2015,Albany,21491.6676
6,2015-11-15,0.99,83453.76,1368.92,73672.72,93.26,8318.86,8196.81,122.05,0.0,conventional,2015,Albany,19928.9049
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7,2018-02-04,1.63,17074.83,2046.96,1529.20,0.00,13498.67,13066.82,431.85,0.0,organic,2018,WestTexNewMexico,22002.8321
8,2018-01-28,1.71,13888.04,1191.70,3431.50,0.00,9264.84,8940.04,324.80,0.0,organic,2018,WestTexNewMexico,15842.8764
9,2018-01-21,1.87,13766.76,1191.92,2452.79,727.94,9394.11,9351.80,42.31,0.0,organic,2018,WestTexNewMexico,17566.9857
10,2018-01-14,1.93,16205.22,1527.63,2981.04,727.01,10969.54,10919.54,50.00,0.0,organic,2018,WestTexNewMexico,21171.2122
11,2018-01-07,1.62,17489.58,2894.77,2356.13,224.53,12014.15,11988.14,26.01,0.0,organic,2018,WestTexNewMexico,19462.9230

### Reemplazar los NA's por la media

In [51]:
promedio = dataset.Aguacates_vendidos.mean()
dataset.Aguacates_vendidos = dataset.Aguacates_vendidos.fillna(promedio)
dataset

C:\Users\jorge\AppData\Local\Temp\ipykernel_1708\363034602.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset.Aguacates_vendidos = dataset.Aguacates_vendidos.fillna(promedio)

,Fecha,Precio_promedio,Aguacates_vendidos,PLU 4046 venta,PLU 4225 venta,PLU 4770 venta,Bolsas_Totales,Bolsas_chicas,Bolsas_grandes,Bolsas_extragrandes,tipo,year,region,Ingresos
0,2015-12-27,30.00,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany,17506.4328
1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany,19252.7088
4,2015-11-29,1.28,51039.60,941.48,43838.39,75.78,6183.95,5986.26,197.69,0.0,conventional,2015,Albany,21923.9981
5,2015-11-22,1.26,55979.78,1184.27,48067.99,43.61,6683.91,6556.47,127.44,0.0,conventional,2015,Albany,21491.6676
6,2015-11-15,0.99,83453.76,1368.92,73672.72,93.26,8318.86,8196.81,122.05,0.0,conventional,2015,Albany,19928.9049
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7,2018-02-04,1.63,17074.83,2046.96,1529.20,0.00,13498.67,13066.82,431.85,0.0,organic,2018,WestTexNewMexico,22002.8321
8,2018-01-28,1.71,13888.04,1191.70,3431.50,0.00,9264.84,8940.04,324.80,0.0,organic,2018,WestTexNewMexico,15842.8764
9,2018-01-21,1.87,13766.76,1191.92,2452.79,727.94,9394.11,9351.80,42.31,0.0,organic,2018,WestTexNewMexico,17566.9857
10,2018-01-14,1.93,16205.22,1527.63,2981.04,727.01,10969.54,10919.54,50.00,0.0,organic,2018,WestTexNewMexico,21171.2122
11,2018-01-07,1.62,17489.58,2894.77,2356.13,224.53,12014.15,11988.14,26.01,0.0,organic,2018,WestTexNewMexico,19462.9230

### Reemplazar los NAs por la mediana

In [52]:
mediana = dataset["Aguacates_vendidos"].median()
dataset["Aguacates_vendidos"].fillna(mediana)
dataset

,Fecha,Precio_promedio,Aguacates_vendidos,PLU 4046 venta,PLU 4225 venta,PLU 4770 venta,Bolsas_Totales,Bolsas_chicas,Bolsas_grandes,Bolsas_extragrandes,tipo,year,region,Ingresos
0,2015-12-27,30.00,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany,17506.4328
1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany,19252.7088
4,2015-11-29,1.28,51039.60,941.48,43838.39,75.78,6183.95,5986.26,197.69,0.0,conventional,2015,Albany,21923.9981
5,2015-11-22,1.26,55979.78,1184.27,48067.99,43.61,6683.91,6556.47,127.44,0.0,conventional,2015,Albany,21491.6676
6,2015-11-15,0.99,83453.76,1368.92,73672.72,93.26,8318.86,8196.81,122.05,0.0,conventional,2015,Albany,19928.9049
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7,2018-02-04,1.63,17074.83,2046.96,1529.20,0.00,13498.67,13066.82,431.85,0.0,organic,2018,WestTexNewMexico,22002.8321
8,2018-01-28,1.71,13888.04,1191.70,3431.50,0.00,9264.84,8940.04,324.80,0.0,organic,2018,WestTexNewMexico,15842.8764
9,2018-01-21,1.87,13766.76,1191.92,2452.79,727.94,9394.11,9351.80,42.31,0.0,organic,2018,WestTexNewMexico,17566.9857
10,2018-01-14,1.93,16205.22,1527.63,2981.04,727.01,10969.54,10919.54,50.00,0.0,organic,2018,WestTexNewMexico,21171.2122
11,2018-01-07,1.62,17489.58,2894.77,2356.13,224.53,12014.15,11988.14,26.01,0.0,organic,2018,WestTexNewMexico,19462.9230

## <font color = darkblue> Transformación de datos

La transformación de datos es el proceso de convertir datos de un formato a otro para que puedan ser utilizados en análisis, informes, almacenamiento, entre otros. La transformación de datos es importante porque ayuda a tener datos de calidad, lo que les permite tomar decisiones más acertadas.

### Identificar los duplicados

In [53]:
dataset.duplicated()

0     False
1     False
4     False
5     False
6     False
      ...
7     False
8     False
9     False
10    False
11    False
Length: 18247, dtype: bool

### Eliminar duplicados

In [54]:
dataset.drop_duplicates(inplace=True)

C:\Users\jorge\AppData\Local\Temp\ipykernel_1708\2870039874.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset.drop_duplicates(inplace=True)

### Cambiar el tipo de datos

In [55]:
dataset["Precio_promedio"] = dataset["Precio_promedio"].astype(int)

C:\Users\jorge\AppData\Local\Temp\ipykernel_1708\30624422.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset["Precio_promedio"] = dataset["Precio_promedio"].astype(int)

### Nueva columna

In [56]:
dataset["Nueva Columna"] = dataset["Precio_promedio"] * 2
dataset

C:\Users\jorge\AppData\Local\Temp\ipykernel_1708\1477862135.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset["Nueva Columna"] = dataset["Precio_promedio"] * 2

,Fecha,Precio_promedio,Aguacates_vendidos,PLU 4046 venta,PLU 4225 venta,PLU 4770 venta,Bolsas_Totales,Bolsas_chicas,Bolsas_grandes,Bolsas_extragrandes,tipo,year,region,Ingresos,Nueva Columna
0,2015-12-27,30,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany,17506.4328,60
1,2015-12-20,1,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany,19252.7088,2
4,2015-11-29,1,51039.60,941.48,43838.39,75.78,6183.95,5986.26,197.69,0.0,conventional,2015,Albany,21923.9981,2
5,2015-11-22,1,55979.78,1184.27,48067.99,43.61,6683.91,6556.47,127.44,0.0,conventional,2015,Albany,21491.6676,2
6,2015-11-15,0,83453.76,1368.92,73672.72,93.26,8318.86,8196.81,122.05,0.0,conventional,2015,Albany,19928.9049,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7,2018-02-04,1,17074.83,2046.96,1529.20,0.00,13498.67,13066.82,431.85,0.0,organic,2018,WestTexNewMexico,22002.8321,2
8,2018-01-28,1,13888.04,1191.70,3431.50,0.00,9264.84,8940.04,324.80,0.0,organic,2018,WestTexNewMexico,15842.8764,2
9,2018-01-21,1,13766.76,1191.92,2452.79,727.94,9394.11,9351.80,42.31,0.0,organic,2018,WestTexNewMexico,17566.9857,2
10,2018-01-14,1,16205.22,1527.63,2981.04,727.01,10969.54,10919.54,50.00,0.0,organic,2018,WestTexNewMexico,21171.2122,2
11,2018-01-07,1,17489.58,2894.77,2356.13,224.53,12014.15,11988.14,26.01,0.0,organic,2018,WestTexNewMexico,19462.9230,2

### Algunos estadísticos

In [57]:
media_mpg = dataset["Precio_promedio"].mean()     # Media
print(media_mpg)
mediana_mpg = dataset["Precio_promedio"].median()   # Mediana
print(mediana_mpg)
sd_mpg = dataset["Precio_promedio"].std()   # Desviacion estandar
sd_mpg

0.927988162437661
1.0

0.52397190302505

## <font color = darkblue> Manejo de datos categóricos

### One hot encoding

In [58]:
dataset_dummies = pd.get_dummies(dataset, columns = ["tipo"])
dataset_dummies.columns.values

array(['Fecha', 'Precio_promedio', 'Aguacates_vendidos', 'PLU 4046 venta',
       'PLU 4225 venta', 'PLU 4770 venta', 'Bolsas_Totales',
       'Bolsas_chicas', 'Bolsas_grandes', 'Bolsas_extragrandes', 'year',
       'region', 'Ingresos', 'Nueva Columna', 'tipo_conventional',
       'tipo_organic'], dtype=object)

In [59]:
dataset_dummies.head(3)

,Fecha,Precio_promedio,Aguacates_vendidos,PLU 4046 venta,PLU 4225 venta,PLU 4770 venta,Bolsas_Totales,Bolsas_chicas,Bolsas_grandes,Bolsas_extragrandes,year,region,Ingresos,Nueva Columna,tipo_conventional,tipo_organic
0,2015-12-27,30,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,2015,Albany,17506.4328,60,True,False
1,2015-12-20,1,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,2015,Albany,19252.7088,2,True,False
4,2015-11-29,1,51039.60,941.48,43838.39,75.78,6183.95,5986.26,197.69,0.0,2015,Albany,21923.9981,2,True,False

In [60]:
dataset_dummies = pd.get_dummies(dataset, columns = ["region"])
dataset_dummies.columns.values

array(['Fecha', 'Precio_promedio', 'Aguacates_vendidos', 'PLU 4046 venta',
       'PLU 4225 venta', 'PLU 4770 venta', 'Bolsas_Totales',
       'Bolsas_chicas', 'Bolsas_grandes', 'Bolsas_extragrandes', 'tipo',
       'year', 'Ingresos', 'Nueva Columna', 'region_Albany',
       'region_Atlanta', 'region_BaltimoreWashington', 'region_Boise',
       'region_Boston', 'region_BuffaloRochester', 'region_California',
       'region_Charlotte', 'region_Chicago', 'region_CincinnatiDayton',
       'region_Columbus', 'region_DallasFtWorth', 'region_Denver',
       'region_Detroit', 'region_GrandRapids', 'region_GreatLakes',
       'region_HarrisburgScranton', 'region_HartfordSpringfield',
       'region_Houston', 'region_Indianapolis', 'region_Jacksonville',
       'region_LasVegas', 'region_LosAngeles', 'region_Louisville',
       'region_MiamiFtLauderdale', 'region_Midsouth', 'region_Nashville',
       'region_NewOrleansMobile', 'region_NewYork', 'region_Northeast',
       'region_NorthernNewEngland', 'region_Orlando',
       'region_Philadelphia', 'region_PhoenixTucson', 'region_Pittsburgh',
       'region_Plains', 'region_Portland', 'region_RaleighGreensboro',
       'region_RichmondNorfolk', 'region_Roanoke', 'region_Sacramento',
       'region_SanDiego', 'region_SanFrancisco', 'region_Seattle',
       'region_SouthCarolina', 'region_SouthCentral', 'region_Southeast',
       'region_Spokane', 'region_StLouis', 'region_Syracuse',
       'region_Tampa', 'region_TotalUS', 'region_West',
       'region_WestTexNewMexico'], dtype=object)

In [62]:
dataset_dummies

,Fecha,Precio_promedio,Aguacates_vendidos,PLU 4046 venta,PLU 4225 venta,PLU 4770 venta,Bolsas_Totales,Bolsas_chicas,Bolsas_grandes,Bolsas_extragrandes,...,region_SouthCarolina,region_SouthCentral,region_Southeast,region_Spokane,region_StLouis,region_Syracuse,region_Tampa,region_TotalUS,region_West,region_WestTexNewMexico
0,2015-12-27,30,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,...,False,False,False,False,False,False,False,False,False,False
1,2015-12-20,1,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,...,False,False,False,False,False,False,False,False,False,False
4,2015-11-29,1,51039.60,941.48,43838.39,75.78,6183.95,5986.26,197.69,0.0,...,False,False,False,False,False,False,False,False,False,False
5,2015-11-22,1,55979.78,1184.27,48067.99,43.61,6683.91,6556.47,127.44,0.0,...,False,False,False,False,False,False,False,False,False,False
6,2015-11-15,0,83453.76,1368.92,73672.72,93.26,8318.86,8196.81,122.05,0.0,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7,2018-02-04,1,17074.83,2046.96,1529.20,0.00,13498.67,13066.82,431.85,0.0,...,False,False,False,False,False,False,False,False,False,True
8,2018-01-28,1,13888.04,1191.70,3431.50,0.00,9264.84,8940.04,324.80,0.0,...,False,False,False,False,False,False,False,False,False,True
9,2018-01-21,1,13766.76,1191.92,2452.79,727.94,9394.11,9351.80,42.31,0.0,...,False,False,False,False,False,False,False,False,False,True
10,2018-01-14,1,16205.22,1527.63,2981.04,727.01,10969.54,10919.54,50.00,0.0,...,False,False,False,False,False,False,False,False,False,True
11,2018-01-07,1,17489.58,2894.77,2356.13,224.53,12014.15,11988.14,26.01,0.0,...,False,False,False,False,False,False,False,False,False,True

### Ordinal

In [64]:
from sklearn.preprocessing import LabelEncoder
Encoder = LabelEncoder()
dataset['region'] = Encoder.fit_transform(dataset['region'])

C:\Users\jorge\AppData\Local\Temp\ipykernel_1708\3799993844.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset['region'] = Encoder.fit_transform(dataset['region'])

In [66]:
dataset.tail(2)

,Fecha,Precio_promedio,Aguacates_vendidos,PLU 4046 venta,PLU 4225 venta,PLU 4770 venta,Bolsas_Totales,Bolsas_chicas,Bolsas_grandes,Bolsas_extragrandes,tipo,year,region,Ingresos,Nueva Columna
10,2018-01-14,1,16205.22,1527.63,2981.04,727.01,10969.54,10919.54,50.00,0.0,organic,2018,53,21171.2122,2
11,2018-01-07,1,17489.58,2894.77,2356.13,224.53,12014.15,11988.14,26.01,0.0,organic,2018,53,19462.9230,2

## <font color = darkblue> Normalización, escalamiento y estandarización

En Machine Learning y ciencia de datos, los datos deben estar en un rango o formato uniforme para garantizar que los algoritmos funcionen correctamente. Aquí es donde entran en juego las técnicas de normalización, escalamiento y estandarización. Vamos a explicar cada una:

<center> <img src = "Normalizacion_estandarizacion_escalamiento.png" width="600"></center>

### Normalización
La normalización consiste en reescalar los valores de las características (features) para que queden en un rango específico, generalmente entre 0 y 1. Es útil cuando los datos no siguen una distribución normal o cuando se quiere limitar los valores.


<center> $$x' = \frac{x - x_{min}}{x_{max} - x_{min}}$$</center>

donde $x$ es el valor original, $x_{min}$ es el valor mínimo de la característica, $x_{max}$ es el valor máximo de la característica, y $x'$ es el valor normalizado.

Esta técnica se utiliza cuando los datos tienen escalas muy diferentes y no tienen una distribución normal. También cuando se requiere que los valores estén en un rango definido.

In [58]:
from sklearn.preprocessing import MinMaxScaler

In [59]:
# Datos originales
datos = [[1], [2], [3], [4], [5]]

# Normalización
scaler = MinMaxScaler()
datos_normalizados = scaler.fit_transform(datos)
datos_normalizados

array([[0.  ],
       [0.25],
       [0.5 ],
       [0.75],
       [1.  ]])

### Escalamiento

El escalamiento ajusta los datos para que estén dentro de un rango específico, pero no necesariamente entre 0 y 1. Esto incluye técnicas como dividir entre un valor constante o trabajar con logaritmos.

<center> $$x' = \frac{x}{\max{(|x|)}}$$</center>

Se debe usar cuando la escala de los datos es importante para la interpretación, pero no necesitas que esté en un rango fijo. Y cuando algunos modelos son sensibles a las magnitudes de las características.

In [60]:
from sklearn.preprocessing import MaxAbsScaler

In [61]:
# Datos originales
datos = [[-1], [0], [1], [2], [3]]

# Escalamiento basado en el máximo absoluto
scaler = MaxAbsScaler()
datos_escalados = scaler.fit_transform(datos)
datos_escalados

array([[-0.33333333],
       [ 0.        ],
       [ 0.33333333],
       [ 0.66666667],
       [ 1.        ]])

### Estandarización

La estandarización transforma los datos para que tengan una media ($\mu$) de $0$ y una desviación estándar ($\sigma$) de $1$. Esto asegura que los datos sigan una distribución normal estándar (o lo más cercana posible).

<center> $$z = \frac{x-\mu}{\sigma}$$</center>

donde $\mu$ es la media de la característica, $\sigma$ es la desviación estándar de la característica, y $z$ es el valor estandarizado.

Se debe usar cuando los datos siguen una distribución normal o casi normal. También, cuando se utilizan modelos que asumen distribuciones normales, como la regresión logística, SVM o redes neuronales.

In [62]:
from sklearn.preprocessing import StandardScaler

In [63]:
# Datos originales
datos = [[1], [2], [3], [4], [5]]

# Estandarización
scaler = StandardScaler()
datos_estandarizados = scaler.fit_transform(datos)

datos_estandarizados

array([[-1.41421356],
       [-0.70710678],
       [ 0.        ],
       [ 0.70710678],
       [ 1.41421356]])